// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Reddit.Ads.OpenApiClient.Generated_content.Posters;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Generated_content
{
    /// <summary>
    /// Builds and executes requests for operations under \generated_content
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Generated_contentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The posters property</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Generated_content.Posters.PostersRequestBuilder Posters
        {
            get => new global::Soenneker.Reddit.Ads.OpenApiClient.Generated_content.Posters.PostersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Generated_content.Generated_contentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Generated_contentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/generated_content", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Generated_content.Generated_contentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Generated_contentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/generated_content", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
