// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>
    /// Forecast ranges for the outcomes based on the provided campaign and ad group configurations. Only available outcomes are included. See [optimization goal options](/docs/v3/api/create-ad-group#optimization-goal-options) for how goals are grouped by campaign objective.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AudienceAndDeliveryEstimates200ResponseDataDeliveryEstimates : IParsable
    {
        /// <summary>The clicks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate? Clicks { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate Clicks { get; set; }
#endif
        /// <summary>The conversions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate? Conversions { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate Conversions { get; set; }
#endif
        /// <summary>The impressions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate? Impressions { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate Impressions { get; set; }
#endif
        /// <summary>The installs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate? Installs { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate Installs { get; set; }
#endif
        /// <summary>The post_installs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate? PostInstalls { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate PostInstalls { get; set; }
#endif
        /// <summary>The reach property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate? Reach { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate Reach { get; set; }
#endif
        /// <summary>The video_views property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate? VideoViews { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate VideoViews { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.AudienceAndDeliveryEstimates200ResponseDataDeliveryEstimates"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.AudienceAndDeliveryEstimates200ResponseDataDeliveryEstimates CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.AudienceAndDeliveryEstimates200ResponseDataDeliveryEstimates();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clicks", n => { Clicks = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate.CreateFromDiscriminatorValue); } },
                { "conversions", n => { Conversions = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate.CreateFromDiscriminatorValue); } },
                { "impressions", n => { Impressions = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate.CreateFromDiscriminatorValue); } },
                { "installs", n => { Installs = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate.CreateFromDiscriminatorValue); } },
                { "post_installs", n => { PostInstalls = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate.CreateFromDiscriminatorValue); } },
                { "reach", n => { Reach = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate.CreateFromDiscriminatorValue); } },
                { "video_views", n => { VideoViews = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>("clicks", Clicks);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>("conversions", Conversions);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>("impressions", Impressions);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>("installs", Installs);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>("post_installs", PostInstalls);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>("reach", Reach);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeliveryEstimate>("video_views", VideoViews);
        }
    }
}
#pragma warning restore CS0618
