// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesAdGroupGoalValue"/>, <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesCampaignGoalValue"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AudienceAndDeliveryEstimatesRequestData : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesAdGroupGoalValue"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesAdGroupGoalValue? ComponentsSchemaForecastingEstimatesAdGroupGoalValue { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesAdGroupGoalValue ComponentsSchemaForecastingEstimatesAdGroupGoalValue { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesCampaignGoalValue"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesCampaignGoalValue? ComponentsSchemaForecastingEstimatesCampaignGoalValue { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesCampaignGoalValue ComponentsSchemaForecastingEstimatesCampaignGoalValue { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.AudienceAndDeliveryEstimatesRequestData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.AudienceAndDeliveryEstimatesRequestData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Reddit.Ads.OpenApiClient.Models.AudienceAndDeliveryEstimatesRequestData();
            if("ComponentsSchemaForecastingEstimatesAdGroupGoalValue".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ComponentsSchemaForecastingEstimatesAdGroupGoalValue = new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesAdGroupGoalValue();
            }
            else if("ComponentsSchemaForecastingEstimatesCampaignGoalValue".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ComponentsSchemaForecastingEstimatesCampaignGoalValue = new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesCampaignGoalValue();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ComponentsSchemaForecastingEstimatesAdGroupGoalValue != null)
            {
                return ComponentsSchemaForecastingEstimatesAdGroupGoalValue.GetFieldDeserializers();
            }
            else if(ComponentsSchemaForecastingEstimatesCampaignGoalValue != null)
            {
                return ComponentsSchemaForecastingEstimatesCampaignGoalValue.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ComponentsSchemaForecastingEstimatesAdGroupGoalValue != null)
            {
                writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesAdGroupGoalValue>(null, ComponentsSchemaForecastingEstimatesAdGroupGoalValue);
            }
            else if(ComponentsSchemaForecastingEstimatesCampaignGoalValue != null)
            {
                writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaForecastingEstimatesCampaignGoalValue>(null, ComponentsSchemaForecastingEstimatesCampaignGoalValue);
            }
        }
    }
}
#pragma warning restore CS0618
