// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The ad group&apos;s [bidding strategy](https://business.reddithelp.com/s/article/How-much-do-Reddit-Ads-cost#bidding-strategies).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BidType3
    {
        [EnumMember(Value = "CPC")]
        #pragma warning disable CS1591
        Cpc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CPM")]
        #pragma warning disable CS1591
        Cpm,
        #pragma warning restore CS1591
        [EnumMember(Value = "CPV")]
        #pragma warning disable CS1591
        Cpv,
        #pragma warning restore CS1591
        [EnumMember(Value = "CPV6")]
        #pragma warning disable CS1591
        Cpv6,
        #pragma warning restore CS1591
        [EnumMember(Value = "CPV15")]
        #pragma warning disable CS1591
        Cpv15,
        #pragma warning restore CS1591
    }
}
