// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>
    /// Configuration for a Lookalike audience. Required when the Custom Audience Type is LOOKALIKE.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComponentsSchemaLookalikeConfig : IParsable
    {
        /// <summary>The audience size type.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLookalikeConfigAudienceSize? AudienceSize { get; set; }
        /// <summary>The ID of the [website retargeting](https://business.reddithelp.com/s/article/custom-audiences#website-retargeting) or [customer list audience](https://business.reddithelp.com/s/article/custom-audiences#customer-lists) used to generate this audience.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceAudienceId { get; set; }
#nullable restore
#else
        public string SourceAudienceId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLookalikeConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLookalikeConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLookalikeConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audience_size", n => { AudienceSize = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLookalikeConfigAudienceSize>(); } },
                { "source_audience_id", n => { SourceAudienceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLookalikeConfigAudienceSize>("audience_size", AudienceSize);
            writer.WriteStringValue("source_audience_id", SourceAudienceId);
        }
    }
}
#pragma warning restore CS0618
