// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>
    /// The Pixel&apos;s [automated advanced matching](https://business.reddithelp.com/s/article/automated-advanced-matching) settings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComponentsSchemaAutomaticAdvancedMatchingConfig : IParsable
    {
        /// <summary>Whether to automatically collect email addresses.</summary>
        public bool? CollectEmail { get; set; }
        /// <summary>Whether to automatically collect phone numbers.</summary>
        public bool? CollectPhoneNumber { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAutomaticAdvancedMatchingConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAutomaticAdvancedMatchingConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAutomaticAdvancedMatchingConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collect_email", n => { CollectEmail = n.GetBoolValue(); } },
                { "collect_phone_number", n => { CollectPhoneNumber = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("collect_email", CollectEmail);
            writer.WriteBoolValue("collect_phone_number", CollectPhoneNumber);
        }
    }
}
#pragma warning restore CS0618
