// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The device type to target.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaDeviceTargetType
    {
        [EnumMember(Value = "DESKTOP")]
        #pragma warning disable CS1591
        Desktop,
        #pragma warning restore CS1591
        [EnumMember(Value = "MOBILE")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
    }
}
