// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The audience&apos;s external source.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaCustomerListConfigOrigin
    {
        [EnumMember(Value = "UNSPECIFIED")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIVE_RAMP")]
        #pragma warning disable CS1591
        LiveRamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "MPARTICLE")]
        #pragma warning disable CS1591
        Mparticle,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEALIUM")]
        #pragma warning disable CS1591
        Tealium,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIVE_RAMP_ADVERTISER_DIRECT")]
        #pragma warning disable CS1591
        LiveRampAdvertiserDirect,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOMBORA")]
        #pragma warning disable CS1591
        Bombora,
        #pragma warning restore CS1591
    }
}
