// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The question type to show on the form.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaLeadGenFormQuestionType
    {
        [EnumMember(Value = "EMAIL")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIRST_NAME")]
        #pragma warning disable CS1591
        FirstName,
        #pragma warning restore CS1591
        [EnumMember(Value = "LAST_NAME")]
        #pragma warning disable CS1591
        LastName,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHONE_NUMBER")]
        #pragma warning disable CS1591
        PhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTAL_CODE")]
        #pragma warning disable CS1591
        PostalCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "JOB_TITLE")]
        #pragma warning disable CS1591
        JobTitle,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPANY")]
        #pragma warning disable CS1591
        Company,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPANY_EMAIL")]
        #pragma warning disable CS1591
        CompanyEmail,
        #pragma warning restore CS1591
    }
}
