// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ComponentsParametersCreativeAssetMimeTypeItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "image/jpeg")]
        #pragma warning disable CS1591
        ImageJpeg,
        #pragma warning restore CS1591
        [EnumMember(Value = "image/png")]
        #pragma warning disable CS1591
        ImagePng,
        #pragma warning restore CS1591
        [EnumMember(Value = "image/gif")]
        #pragma warning disable CS1591
        ImageGif,
        #pragma warning restore CS1591
        [EnumMember(Value = "image/webp")]
        #pragma warning disable CS1591
        ImageWebp,
        #pragma warning restore CS1591
        [EnumMember(Value = "video/mp4")]
        #pragma warning disable CS1591
        VideoMp4,
        #pragma warning restore CS1591
        [EnumMember(Value = "video/quicktime")]
        #pragma warning disable CS1591
        VideoQuicktime,
        #pragma warning restore CS1591
    }
}
