// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The calculated status determining the real status of this entity.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaAdBaseEffectiveStatus
    {
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "AD_GROUP_PAUSED")]
        #pragma warning disable CS1591
        AdGroupPaused,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARCHIVED")]
        #pragma warning disable CS1591
        Archived,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAMPAIGN_PAUSED")]
        #pragma warning disable CS1591
        CampaignPaused,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETED")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_PERMISSIONS")]
        #pragma warning disable CS1591
        MissingPermissions,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAUSED")]
        #pragma warning disable CS1591
        Paused,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_APPROVAL")]
        #pragma warning disable CS1591
        PendingApproval,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_BILLING_INFO")]
        #pragma warning disable CS1591
        PendingBillingInfo,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_ID_VERIFICATION")]
        #pragma warning disable CS1591
        PendingIdVerification,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESSING")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECTED")]
        #pragma warning disable CS1591
        Rejected,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
