// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The data deletion job&apos;s [current status](/docs/v3/guides/programs/data-deletion/delete-user-data#2-track-the-job-status).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaDataDeletionJobStatusStatus
    {
        [EnumMember(Value = "QUEUED")]
        #pragma warning disable CS1591
        Queued,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
