// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaShoppingTargeting : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>[Conversion events](https://business.reddithelp.com/s/article/supported-conversion-events) to target. Used when `targeting_type` is `RETARGETING`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsConversionEventType?>? ConversionEventTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsConversionEventType?> ConversionEventTypes { get; set; }
#endif
        /// <summary>Conversion events to exclude from targeting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsConversionEventType?>? ExcludedConversionEventTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsConversionEventType?> ExcludedConversionEventTypes { get; set; }
#endif
        /// <summary>How far back (in days) to look for user actions to include for targeting.</summary>
        public int? LookbackWindowDays { get; set; }
        /// <summary>The `CATALOG_SALES` ad&apos;s [audience type](https://business.reddithelp.com/s/article/dynamic-product-ads#2-create-your-ad-group).</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingTargetingTargetingType? TargetingType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingTargeting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingTargeting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingTargeting();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "conversion_event_types", n => { ConversionEventTypes = n.GetCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsConversionEventType>()?.AsList(); } },
                { "excluded_conversion_event_types", n => { ExcludedConversionEventTypes = n.GetCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsConversionEventType>()?.AsList(); } },
                { "lookback_window_days", n => { LookbackWindowDays = n.GetIntValue(); } },
                { "targeting_type", n => { TargetingType = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingTargetingTargetingType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsConversionEventType>("conversion_event_types", ConversionEventTypes);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsConversionEventType>("excluded_conversion_event_types", ExcludedConversionEventTypes);
            writer.WriteIntValue("lookback_window_days", LookbackWindowDays);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingTargetingTargetingType>("targeting_type", TargetingType);
        }
    }
}
#pragma warning restore CS0618
