// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>
    /// Create a dynamic creative template ad in an automated Reddit Max ad group. Reddit uses the supplied creative assets and destination to generate ads for delivery. Materialization state and errors are returned by the service. See the [Max campaign setup guide](/docs/v3/guides/programs/campaign/max-campaign-setup) for the complete creation workflow.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComponentsSchemaAdCreateDynamicCreativeTemplate : IAdditionalDataHolder, IParsable
    {
        /// <summary>The ad_account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdAccountId { get; set; }
#nullable restore
#else
        public string AdAccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the ad group this ad belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdGroupId { get; set; }
#nullable restore
#else
        public string AdGroupId { get; set; }
#endif
        /// <summary>Creative asset identifiers. Supply at least 3 distinct headline assets and 2 distinct media assets. The service validates asset ownership, type, status, and version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>? AssetIdentifiers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId> AssetIdentifiers { get; set; }
#endif
        /// <summary>Optional query parameters to be appended to the `click_url`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter>? ClickUrlQueryParameters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter> ClickUrlQueryParameters { get; set; }
#endif
        /// <summary>The ad&apos;s status set by the ad account. Can differ from `effective_status` depending on context, such as pending billing information.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ConfiguredStatus2? ConfiguredStatus { get; set; }
        /// <summary>A URL to navigate the user to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesDestinationsUrl? Destination { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesDestinationsUrl Destination { get; set; }
#endif
        /// <summary>Details about enhancements associated with the creative.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesEnhancements? Enhancements { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesEnhancements Enhancements { get; set; }
#endif
        /// <summary>URLs to be called on certain events. Only URLs from Reddit&apos;s list of [approved measurement providers](https://business.reddithelp.com/s/article/Set-up-third-party-measurement) are allowed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem>? EventTrackers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem> EventTrackers { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>When the link for `preview_url` will no longer work. Set to `null` to disable the preview URL. [Learn how to update this field](https://ads-api.reddit.com/docs/v3/preview-an-ad).</summary>
        public DateTimeOffset? PreviewExpiry { get; set; }
        /// <summary>The profile that owns the template&apos;s creative assets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileId { get; set; }
#nullable restore
#else
        public string ProfileId { get; set; }
#endif
        /// <summary>Optional supplementary or disclaimer text for the generated post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupplementaryText { get; set; }
#nullable restore
#else
        public string SupplementaryText { get; set; }
#endif
        /// <summary>Optional image asset identifiers used as video thumbnails.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>? ThumbnailAssetIdentifiers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId> ThumbnailAssetIdentifiers { get; set; }
#endif
        /// <summary>The ad type used for a Reddit Max creative template.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.DynamicCreativeAdTemplateType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdCreateDynamicCreativeTemplate"/> and sets the default values.
        /// </summary>
        public ComponentsSchemaAdCreateDynamicCreativeTemplate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdCreateDynamicCreativeTemplate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdCreateDynamicCreativeTemplate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdCreateDynamicCreativeTemplate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ad_account_id", n => { AdAccountId = n.GetStringValue(); } },
                { "ad_group_id", n => { AdGroupId = n.GetStringValue(); } },
                { "asset_identifiers", n => { AssetIdentifiers = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId.CreateFromDiscriminatorValue)?.AsList(); } },
                { "click_url_query_parameters", n => { ClickUrlQueryParameters = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "configured_status", n => { ConfiguredStatus = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ConfiguredStatus2>(); } },
                { "destination", n => { Destination = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesDestinationsUrl>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesDestinationsUrl.CreateFromDiscriminatorValue); } },
                { "enhancements", n => { Enhancements = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesEnhancements>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesEnhancements.CreateFromDiscriminatorValue); } },
                { "event_trackers", n => { EventTrackers = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "preview_expiry", n => { PreviewExpiry = n.GetDateTimeOffsetValue(); } },
                { "profile_id", n => { ProfileId = n.GetStringValue(); } },
                { "supplementary_text", n => { SupplementaryText = n.GetStringValue(); } },
                { "thumbnail_asset_identifiers", n => { ThumbnailAssetIdentifiers = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.DynamicCreativeAdTemplateType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ad_account_id", AdAccountId);
            writer.WriteStringValue("ad_group_id", AdGroupId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>("asset_identifiers", AssetIdentifiers);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter>("click_url_query_parameters", ClickUrlQueryParameters);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ConfiguredStatus2>("configured_status", ConfiguredStatus);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesDestinationsUrl>("destination", Destination);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesEnhancements>("enhancements", Enhancements);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem>("event_trackers", EventTrackers);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("preview_expiry", PreviewExpiry);
            writer.WriteStringValue("profile_id", ProfileId);
            writer.WriteStringValue("supplementary_text", SupplementaryText);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>("thumbnail_asset_identifiers", ThumbnailAssetIdentifiers);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.DynamicCreativeAdTemplateType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
