// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ComponentsSchemaPixelAudienceConfigTargetingsItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PAGE_VISIT")]
        #pragma warning disable CS1591
        PageVisit,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIEW_CONTENT")]
        #pragma warning disable CS1591
        ViewContent,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEARCH")]
        #pragma warning disable CS1591
        Search,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADD_TO_CART")]
        #pragma warning disable CS1591
        AddToCart,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADD_TO_WISHLIST")]
        #pragma warning disable CS1591
        AddToWishlist,
        #pragma warning restore CS1591
        [EnumMember(Value = "PURCHASE")]
        #pragma warning disable CS1591
        Purchase,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEAD")]
        #pragma warning disable CS1591
        Lead,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIGN_UP")]
        #pragma warning disable CS1591
        SignUp,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
