// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaProductCatalog : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The business ID.</summary>
        public Guid? BusinessId { get; set; }
        /// <summary>When this entity was created ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The catalog data sources.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogDataSourcesItem?>? DataSources { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogDataSourcesItem?> DataSources { get; set; }
#endif
        /// <summary>The catalog&apos;s default currency.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogDefaultCurrency? DefaultCurrency { get; set; }
        /// <summary>The catalog&apos;s default language.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogDefaultLanguage? DefaultLanguage { get; set; }
        /// <summary>The attached Reddit Pixel IDs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EventSources { get; set; }
#nullable restore
#else
        public List<string> EventSources { get; set; }
#endif
        /// <summary>The product catalog ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>When this entity was last changed ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>The product catalog&apos;s name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>An overview of the catalog&apos;s product approvals.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogSummary? Summary { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogSummary Summary { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalog"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalog CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalog();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "business_id", n => { BusinessId = n.GetGuidValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "data_sources", n => { DataSources = n.GetCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogDataSourcesItem>()?.AsList(); } },
                { "default_currency", n => { DefaultCurrency = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogDefaultCurrency>(); } },
                { "default_language", n => { DefaultLanguage = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogDefaultLanguage>(); } },
                { "event_sources", n => { EventSources = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "modified_at", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "summary", n => { Summary = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogSummary>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogSummary.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("business_id", BusinessId);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogDataSourcesItem>("data_sources", DataSources);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogDefaultCurrency>("default_currency", DefaultCurrency);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogDefaultLanguage>("default_language", DefaultLanguage);
            writer.WriteCollectionOfPrimitiveValues<string>("event_sources", EventSources);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("modified_at", ModifiedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductCatalogSummary>("summary", Summary);
        }
    }
}
#pragma warning restore CS0618
