// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ComponentsParametersCreativeAssetTypesItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "IMAGE")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIDEO")]
        #pragma warning disable CS1591
        Video,
        #pragma warning restore CS1591
    }
}
