// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The audience size type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaLookalikeConfigAudienceSize
    {
        [EnumMember(Value = "NARROW")]
        #pragma warning disable CS1591
        Narrow,
        #pragma warning restore CS1591
        [EnumMember(Value = "BALANCED")]
        #pragma warning disable CS1591
        Balanced,
        #pragma warning restore CS1591
        [EnumMember(Value = "BROAD")]
        #pragma warning disable CS1591
        Broad,
        #pragma warning restore CS1591
    }
}
