// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaAdCreateStandard : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ad_account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdAccountId { get; set; }
#nullable restore
#else
        public string AdAccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the ad group this ad belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdGroupId { get; set; }
#nullable restore
#else
        public string AdGroupId { get; set; }
#endif
        /// <summary>The URL users are directed to when they click the ad. When `shopping_creative` is set (catalog/product ads), `click_url` is not used for ad delivery; if both are sent in create or update requests, `click_url` is ignored.&gt; **Important:** Updating an ad or creative may update `destination_url`, which `click_url` often needs to match. [Update `click_url` to match its value](/docs/v3/guides/programs/campaign/match-destination-and-click-url) for **image**, **carousel**, or **video** formats.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClickUrl { get; set; }
#nullable restore
#else
        public string ClickUrl { get; set; }
#endif
        /// <summary>Optional query parameters to be appended to the `click_url`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter>? ClickUrlQueryParameters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter> ClickUrlQueryParameters { get; set; }
#endif
        /// <summary>The ad&apos;s status set by the ad account. Can differ from `effective_status` depending on context, such as pending billing information.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ConfiguredStatus2? ConfiguredStatus { get; set; }
        /// <summary>URLs to be called on certain events. Only URLs from Reddit&apos;s list of [approved measurement providers](https://business.reddithelp.com/s/article/Set-up-third-party-measurement) are allowed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem>? EventTrackers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem> EventTrackers { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ad&apos;s post ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostId { get; set; }
#nullable restore
#else
        public string PostId { get; set; }
#endif
        /// <summary>When the link for `preview_url` will no longer work. Set to `null` to disable the preview URL. [Learn how to update this field](https://ads-api.reddit.com/docs/v3/preview-an-ad).</summary>
        public DateTimeOffset? PreviewExpiry { get; set; }
        /// <summary>Products associated with the ad. Up to 6 products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdProduct>? Products { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdProduct> Products { get; set; }
#endif
        /// <summary>The ID of the ad post&apos;s author. Required for catalog sales campaigns.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileId { get; set; }
#nullable restore
#else
        public string ProfileId { get; set; }
#endif
        /// <summary>The shopping_creative property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingCreative? ShoppingCreative { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingCreative ShoppingCreative { get; set; }
#endif
        /// <summary>The ad type.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.UnspecifiedType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdCreateStandard"/> and sets the default values.
        /// </summary>
        public ComponentsSchemaAdCreateStandard()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdCreateStandard"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdCreateStandard CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdCreateStandard();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ad_account_id", n => { AdAccountId = n.GetStringValue(); } },
                { "ad_group_id", n => { AdGroupId = n.GetStringValue(); } },
                { "click_url", n => { ClickUrl = n.GetStringValue(); } },
                { "click_url_query_parameters", n => { ClickUrlQueryParameters = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "configured_status", n => { ConfiguredStatus = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ConfiguredStatus2>(); } },
                { "event_trackers", n => { EventTrackers = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "post_id", n => { PostId = n.GetStringValue(); } },
                { "preview_expiry", n => { PreviewExpiry = n.GetDateTimeOffsetValue(); } },
                { "products", n => { Products = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdProduct>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdProduct.CreateFromDiscriminatorValue)?.AsList(); } },
                { "profile_id", n => { ProfileId = n.GetStringValue(); } },
                { "shopping_creative", n => { ShoppingCreative = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingCreative>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingCreative.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.UnspecifiedType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ad_account_id", AdAccountId);
            writer.WriteStringValue("ad_group_id", AdGroupId);
            writer.WriteStringValue("click_url", ClickUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter>("click_url_query_parameters", ClickUrlQueryParameters);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ConfiguredStatus2>("configured_status", ConfiguredStatus);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem>("event_trackers", EventTrackers);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("post_id", PostId);
            writer.WriteDateTimeOffsetValue("preview_expiry", PreviewExpiry);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdProduct>("products", Products);
            writer.WriteStringValue("profile_id", ProfileId);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingCreative>("shopping_creative", ShoppingCreative);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.UnspecifiedType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
