// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The status of creating and updating ads from the template&apos;s creative inputs.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaDynamicCreativeAdConfigTemplateMaterializationStatus
    {
        [EnumMember(Value = "UNSPECIFIED")]
        #pragma warning disable CS1591
        Unspecified,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTIAL")]
        #pragma warning disable CS1591
        Partial,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUCCESS")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
