// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaProduct : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The product&apos;s additional image URLs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AdditionalImageLinks { get; set; }
#nullable restore
#else
        public List<string> AdditionalImageLinks { get; set; }
#endif
        /// <summary>Whether the product is intended for adults.</summary>
        public bool? Adult { get; set; }
        /// <summary>The target age group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AgeGroup { get; set; }
#nullable restore
#else
        public string AgeGroup { get; set; }
#endif
        /// <summary>The product availability.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsProductAvailabilityStatus? Availability { get; set; }
        /// <summary>The average customer review rating.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AverageReviewRating { get; set; }
#nullable restore
#else
        public string AverageReviewRating { get; set; }
#endif
        /// <summary>The manufacturer brand.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Brand { get; set; }
#nullable restore
#else
        public string Brand { get; set; }
#endif
        /// <summary>The product&apos;s color.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The product&apos;s condition.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Condition { get; set; }
#nullable restore
#else
        public string Condition { get; set; }
#endif
        /// <summary>The merchant&apos;s product cost, including currency ([ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CostOfGoodsSold { get; set; }
#nullable restore
#else
        public string CostOfGoodsSold { get; set; }
#endif
        /// <summary>When this entity was created ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Custom text assigned to a product. Enables filtering and selection of products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomLabel0 { get; set; }
#nullable restore
#else
        public string CustomLabel0 { get; set; }
#endif
        /// <summary>Custom text assigned to a product. Enables filtering and selection of products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomLabel1 { get; set; }
#nullable restore
#else
        public string CustomLabel1 { get; set; }
#endif
        /// <summary>Custom text assigned to a product. Enables filtering and selection of products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomLabel2 { get; set; }
#nullable restore
#else
        public string CustomLabel2 { get; set; }
#endif
        /// <summary>Custom text assigned to a product. Enables filtering and selection of products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomLabel3 { get; set; }
#nullable restore
#else
        public string CustomLabel3 { get; set; }
#endif
        /// <summary>Custom text assigned to a product. Enables filtering and selection of products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomLabel4 { get; set; }
#nullable restore
#else
        public string CustomLabel4 { get; set; }
#endif
        /// <summary>Custom integer assigned to a product. Enables filtering and selection of products.</summary>
        public int? CustomNumber0 { get; set; }
        /// <summary>Custom integer assigned to a product. Enables filtering and selection of products.</summary>
        public int? CustomNumber1 { get; set; }
        /// <summary>Custom integer assigned to a product. Enables filtering and selection of products.</summary>
        public int? CustomNumber2 { get; set; }
        /// <summary>Custom integer assigned to a product. Enables filtering and selection of products.</summary>
        public int? CustomNumber3 { get; set; }
        /// <summary>Custom integer assigned to a product. Enables filtering and selection of products.</summary>
        public int? CustomNumber4 { get; set; }
        /// <summary>The product&apos;s description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The product&apos;s expiration date.</summary>
        public DateTimeOffset? ExpirationDate { get; set; }
        /// <summary>The gender for which the product is intended.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gender { get; set; }
#nullable restore
#else
        public string Gender { get; set; }
#endif
        /// <summary>The product&apos;s Google product category. [See the full list of categories](https://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.txt).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GoogleProductCategory { get; set; }
#nullable restore
#else
        public string GoogleProductCategory { get; set; }
#endif
        /// <summary>The product&apos;s Global Trade Item Number (GTIN).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gtin { get; set; }
#nullable restore
#else
        public string Gtin { get; set; }
#endif
        /// <summary>The product ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The product&apos;s image URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageLink { get; set; }
#nullable restore
#else
        public string ImageLink { get; set; }
#endif
        /// <summary>Whether the product is a part of a bundle.</summary>
        public bool? IsBundle { get; set; }
        /// <summary>The product&apos;s item group ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemGroupId { get; set; }
#nullable restore
#else
        public string ItemGroupId { get; set; }
#endif
        /// <summary>The product&apos;s image URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LifestyleImageLink { get; set; }
#nullable restore
#else
        public string LifestyleImageLink { get; set; }
#endif
        /// <summary>The product&apos;s URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Link { get; set; }
#nullable restore
#else
        public string Link { get; set; }
#endif
        /// <summary>The product&apos;s dominant material.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Material { get; set; }
#nullable restore
#else
        public string Material { get; set; }
#endif
        /// <summary>The product&apos;s mobile product landing page URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MobileLink { get; set; }
#nullable restore
#else
        public string MobileLink { get; set; }
#endif
        /// <summary>When this entity was last changed ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>The product&apos;s Manufacturer Part Number (MPN).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mpn { get; set; }
#nullable restore
#else
        public string Mpn { get; set; }
#endif
        /// <summary>The number of customer reviews.</summary>
        public int? NumberOfRatings { get; set; }
        /// <summary>The product&apos;s visible pattern.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pattern { get; set; }
#nullable restore
#else
        public string Pattern { get; set; }
#endif
        /// <summary>Map of platform to platform-specific URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductPlatformSpecificLink? PlatformSpecificLink { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductPlatformSpecificLink PlatformSpecificLink { get; set; }
#endif
        /// <summary>The product&apos;s price, including currency ([ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Price { get; set; }
#nullable restore
#else
        public string Price { get; set; }
#endif
        /// <summary>The product&apos;s details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductDetail { get; set; }
#nullable restore
#else
        public string ProductDetail { get; set; }
#endif
        /// <summary>The product&apos;s highlight.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductHighlight { get; set; }
#nullable restore
#else
        public string ProductHighlight { get; set; }
#endif
        /// <summary>The product&apos;s merchant-defined category.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductType { get; set; }
#nullable restore
#else
        public string ProductType { get; set; }
#endif
        /// <summary>The reddit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductReddit? Reddit { get; private set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductReddit Reddit { get; private set; }
#endif
        /// <summary>The product&apos;s sale price, including currency ([ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalePrice { get; set; }
#nullable restore
#else
        public string SalePrice { get; set; }
#endif
        /// <summary>The date range when `sale_price` is effective ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)). Provide 2 datetime values with time zone, separated by a forward slash (`/`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SalePriceEffectiveDate { get; set; }
#nullable restore
#else
        public string SalePriceEffectiveDate { get; set; }
#endif
        /// <summary>The product size.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Size { get; set; }
#nullable restore
#else
        public string Size { get; set; }
#endif
        /// <summary>The size measurement system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SizeType { get; set; }
#nullable restore
#else
        public string SizeType { get; set; }
#endif
        /// <summary>The product&apos;s title.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProduct"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProduct CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProduct();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additional_image_links", n => { AdditionalImageLinks = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "adult", n => { Adult = n.GetBoolValue(); } },
                { "age_group", n => { AgeGroup = n.GetStringValue(); } },
                { "availability", n => { Availability = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsProductAvailabilityStatus>(); } },
                { "average_review_rating", n => { AverageReviewRating = n.GetStringValue(); } },
                { "brand", n => { Brand = n.GetStringValue(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "condition", n => { Condition = n.GetStringValue(); } },
                { "cost_of_goods_sold", n => { CostOfGoodsSold = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "custom_label_0", n => { CustomLabel0 = n.GetStringValue(); } },
                { "custom_label_1", n => { CustomLabel1 = n.GetStringValue(); } },
                { "custom_label_2", n => { CustomLabel2 = n.GetStringValue(); } },
                { "custom_label_3", n => { CustomLabel3 = n.GetStringValue(); } },
                { "custom_label_4", n => { CustomLabel4 = n.GetStringValue(); } },
                { "custom_number_0", n => { CustomNumber0 = n.GetIntValue(); } },
                { "custom_number_1", n => { CustomNumber1 = n.GetIntValue(); } },
                { "custom_number_2", n => { CustomNumber2 = n.GetIntValue(); } },
                { "custom_number_3", n => { CustomNumber3 = n.GetIntValue(); } },
                { "custom_number_4", n => { CustomNumber4 = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "expiration_date", n => { ExpirationDate = n.GetDateTimeOffsetValue(); } },
                { "gender", n => { Gender = n.GetStringValue(); } },
                { "google_product_category", n => { GoogleProductCategory = n.GetStringValue(); } },
                { "gtin", n => { Gtin = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "image_link", n => { ImageLink = n.GetStringValue(); } },
                { "is_bundle", n => { IsBundle = n.GetBoolValue(); } },
                { "item_group_id", n => { ItemGroupId = n.GetStringValue(); } },
                { "lifestyle_image_link", n => { LifestyleImageLink = n.GetStringValue(); } },
                { "link", n => { Link = n.GetStringValue(); } },
                { "material", n => { Material = n.GetStringValue(); } },
                { "mobile_link", n => { MobileLink = n.GetStringValue(); } },
                { "modified_at", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "mpn", n => { Mpn = n.GetStringValue(); } },
                { "number_of_ratings", n => { NumberOfRatings = n.GetIntValue(); } },
                { "pattern", n => { Pattern = n.GetStringValue(); } },
                { "platform_specific_link", n => { PlatformSpecificLink = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductPlatformSpecificLink>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductPlatformSpecificLink.CreateFromDiscriminatorValue); } },
                { "price", n => { Price = n.GetStringValue(); } },
                { "product_detail", n => { ProductDetail = n.GetStringValue(); } },
                { "product_highlight", n => { ProductHighlight = n.GetStringValue(); } },
                { "product_type", n => { ProductType = n.GetStringValue(); } },
                { "reddit", n => { Reddit = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductReddit>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductReddit.CreateFromDiscriminatorValue); } },
                { "sale_price", n => { SalePrice = n.GetStringValue(); } },
                { "sale_price_effective_date", n => { SalePriceEffectiveDate = n.GetStringValue(); } },
                { "size", n => { Size = n.GetStringValue(); } },
                { "size_type", n => { SizeType = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("additional_image_links", AdditionalImageLinks);
            writer.WriteBoolValue("adult", Adult);
            writer.WriteStringValue("age_group", AgeGroup);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsProductAvailabilityStatus>("availability", Availability);
            writer.WriteStringValue("average_review_rating", AverageReviewRating);
            writer.WriteStringValue("brand", Brand);
            writer.WriteStringValue("color", Color);
            writer.WriteStringValue("condition", Condition);
            writer.WriteStringValue("cost_of_goods_sold", CostOfGoodsSold);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("custom_label_0", CustomLabel0);
            writer.WriteStringValue("custom_label_1", CustomLabel1);
            writer.WriteStringValue("custom_label_2", CustomLabel2);
            writer.WriteStringValue("custom_label_3", CustomLabel3);
            writer.WriteStringValue("custom_label_4", CustomLabel4);
            writer.WriteIntValue("custom_number_0", CustomNumber0);
            writer.WriteIntValue("custom_number_1", CustomNumber1);
            writer.WriteIntValue("custom_number_2", CustomNumber2);
            writer.WriteIntValue("custom_number_3", CustomNumber3);
            writer.WriteIntValue("custom_number_4", CustomNumber4);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("expiration_date", ExpirationDate);
            writer.WriteStringValue("gender", Gender);
            writer.WriteStringValue("google_product_category", GoogleProductCategory);
            writer.WriteStringValue("gtin", Gtin);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("image_link", ImageLink);
            writer.WriteBoolValue("is_bundle", IsBundle);
            writer.WriteStringValue("item_group_id", ItemGroupId);
            writer.WriteStringValue("lifestyle_image_link", LifestyleImageLink);
            writer.WriteStringValue("link", Link);
            writer.WriteStringValue("material", Material);
            writer.WriteStringValue("mobile_link", MobileLink);
            writer.WriteDateTimeOffsetValue("modified_at", ModifiedAt);
            writer.WriteStringValue("mpn", Mpn);
            writer.WriteIntValue("number_of_ratings", NumberOfRatings);
            writer.WriteStringValue("pattern", Pattern);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaProductPlatformSpecificLink>("platform_specific_link", PlatformSpecificLink);
            writer.WriteStringValue("price", Price);
            writer.WriteStringValue("product_detail", ProductDetail);
            writer.WriteStringValue("product_highlight", ProductHighlight);
            writer.WriteStringValue("product_type", ProductType);
            writer.WriteStringValue("sale_price", SalePrice);
            writer.WriteStringValue("sale_price_effective_date", SalePriceEffectiveDate);
            writer.WriteStringValue("size", Size);
            writer.WriteStringValue("size_type", SizeType);
            writer.WriteStringValue("title", Title);
        }
    }
}
#pragma warning restore CS0618
