// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>Why the ad was rejected.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumsRejectionReason
    {
        [EnumMember(Value = "ADULT_CONTENT_PROHIBITED")]
        #pragma warning disable CS1591
        AdultContentProhibited,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADULT_GENERAL")]
        #pragma warning disable CS1591
        AdultGeneral,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALCOHOL")]
        #pragma warning disable CS1591
        Alcohol,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALCOHOL_ADDICTION_AND_TREATMENT_PROGRAMS")]
        #pragma warning disable CS1591
        AlcoholAddictionAndTreatmentPrograms,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALCOHOL_AGE_TARGETING")]
        #pragma warning disable CS1591
        AlcoholAgeTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALCOHOL_GEO_TARGETING")]
        #pragma warning disable CS1591
        AlcoholGeoTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALCOHOL_GLORIFICATION")]
        #pragma warning disable CS1591
        AlcoholGlorification,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALCOHOL_LICENSING_AND_REGISTRATION_UK_ONLY")]
        #pragma warning disable CS1591
        AlcoholLicensingAndRegistrationUkOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALCOHOL_MINORS")]
        #pragma warning disable CS1591
        AlcoholMinors,
        #pragma warning restore CS1591
        [EnumMember(Value = "BRIDGE_PAGE")]
        #pragma warning disable CS1591
        BridgePage,
        #pragma warning restore CS1591
        [EnumMember(Value = "BROKEN_URL")]
        #pragma warning disable CS1591
        BrokenUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAPITALIZATION")]
        #pragma warning disable CS1591
        Capitalization,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAPITALIZING_ON_TRAGEDIES_OR_CRISES")]
        #pragma warning disable CS1591
        CapitalizingOnTragediesOrCrises,
        #pragma warning restore CS1591
        [EnumMember(Value = "CBD")]
        #pragma warning disable CS1591
        Cbd,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTENT")]
        #pragma warning disable CS1591
        Content,
        #pragma warning restore CS1591
        [EnumMember(Value = "COUNTERFEIT")]
        #pragma warning disable CS1591
        Counterfeit,
        #pragma warning restore CS1591
        [EnumMember(Value = "COUNTERFEIT_GOODS")]
        #pragma warning disable CS1591
        CounterfeitGoods,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATING")]
        #pragma warning disable CS1591
        Dating,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATING_DISCRIMINATORY")]
        #pragma warning disable CS1591
        DatingDiscriminatory,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATING_FOCUS_ON_CASUAL_SEX_PROSTITUTION_FETISHES")]
        #pragma warning disable CS1591
        DatingFocusOnCasualSexProstitutionFetishes,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATING_FOCUS_ON_INFIDELITY")]
        #pragma warning disable CS1591
        DatingFocusOnInfidelity,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATING_MAIL_ORDER_BRIDE_SERVICES")]
        #pragma warning disable CS1591
        DatingMailOrderBrideServices,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECEPTIVE")]
        #pragma warning disable CS1591
        Deceptive,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECEPTIVE_MISLEADING_IRRESPONSIBLE_OR_MISLEADING")]
        #pragma warning disable CS1591
        DeceptiveMisleadingIrresponsibleOrMisleading,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECEPTIVE_MISLEADING_USE_OR_COLLECTION_OF_DATA")]
        #pragma warning disable CS1591
        DeceptiveMisleadingUseOrCollectionOfData,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISCLOSURE_PROPER_ACCREDITATION")]
        #pragma warning disable CS1591
        DisclosureProperAccreditation,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISPLAY_URL")]
        #pragma warning disable CS1591
        DisplayUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL_GATED")]
        #pragma warning disable CS1591
        EmailGated,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXCEEDING_CHARACTERS")]
        #pragma warning disable CS1591
        ExceedingCharacters,
        #pragma warning restore CS1591
        [EnumMember(Value = "FACILIATE_ILLEGAL_FRAUDULENT_OR_MISLEADING_BEHAVIOR")]
        #pragma warning disable CS1591
        FaciliateIllegalFraudulentOrMisleadingBehavior,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINANCE_AND_CRYPTO_GEO_TARGETING")]
        #pragma warning disable CS1591
        FinanceAndCryptoGeoTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINANCE_AND_CRYPTO_LICENSING_AND_REGISTRATION")]
        #pragma warning disable CS1591
        FinanceAndCryptoLicensingAndRegistration,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINANCE_AND_CRYPTO_RESTRICTED")]
        #pragma warning disable CS1591
        FinanceAndCryptoRestricted,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINANCE_CRYPTO_EXAGGERATED_CLAIMS")]
        #pragma warning disable CS1591
        FinanceCryptoExaggeratedClaims,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINANCE_CRYPTO_INDIVIDUAL_INVESTMENTS")]
        #pragma warning disable CS1591
        FinanceCryptoIndividualInvestments,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINANCE_CRYPTO_PROHIBITED_PRODUCTS_AND_SERVICES")]
        #pragma warning disable CS1591
        FinanceCryptoProhibitedProductsAndServices,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINANCIAL_CRYPTO_PRODUCTS_AND_SERVICES_GENERAL_REJECTION")]
        #pragma warning disable CS1591
        FinancialCryptoProductsAndServicesGeneralRejection,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINANCIAL_CRYPTO_PRODUCTS_AND_SERVICES_NEED_MANAGEMENT")]
        #pragma warning disable CS1591
        FinancialCryptoProductsAndServicesNeedManagement,
        #pragma warning restore CS1591
        [EnumMember(Value = "GAMBLING")]
        #pragma warning disable CS1591
        Gambling,
        #pragma warning restore CS1591
        [EnumMember(Value = "GAMBLING_ADDICTION_AND_TREATMENT_PROGRAMS")]
        #pragma warning disable CS1591
        GamblingAddictionAndTreatmentPrograms,
        #pragma warning restore CS1591
        [EnumMember(Value = "GAMBLING_AGE_TARGETING")]
        #pragma warning disable CS1591
        GamblingAgeTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "GAMBLING_DRUGS_LICENSING_AND_REGISTRATION")]
        #pragma warning disable CS1591
        GamblingDrugsLicensingAndRegistration,
        #pragma warning restore CS1591
        [EnumMember(Value = "GAMBLING_GEO_TARGETING")]
        #pragma warning disable CS1591
        GamblingGeoTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "GAMBLING_UNREALISTIC_CLAIMS_AND_EXPECTATIONS")]
        #pragma warning disable CS1591
        GamblingUnrealisticClaimsAndExpectations,
        #pragma warning restore CS1591
        [EnumMember(Value = "GRAMMAR")]
        #pragma warning disable CS1591
        Grammar,
        #pragma warning restore CS1591
        [EnumMember(Value = "HAZARDOUS_PRODUCTS")]
        #pragma warning disable CS1591
        HazardousProducts,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEALTH_AND_WELLNESS_EXAGGERATED_CLAIMS")]
        #pragma warning disable CS1591
        HealthAndWellnessExaggeratedClaims,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEALTH_AND_WELLNESS_GEO_TARGETING")]
        #pragma warning disable CS1591
        HealthAndWellnessGeoTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEALTH_AND_WELLNESS_LICENSING_AND_REGISTRATION")]
        #pragma warning disable CS1591
        HealthAndWellnessLicensingAndRegistration,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEALTH_AND_WELLNESS_PHARMA")]
        #pragma warning disable CS1591
        HealthAndWellnessPharma,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEALTH_AND_WELLNESS_PROHIBITED_PRODUCTS")]
        #pragma warning disable CS1591
        HealthAndWellnessProhibitedProducts,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEALTH_GENERAL")]
        #pragma warning disable CS1591
        HealthGeneral,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEC_TARGETING")]
        #pragma warning disable CS1591
        HecTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "ILLEGAL_FRAUD_MISLEADING")]
        #pragma warning disable CS1591
        IllegalFraudMisleading,
        #pragma warning restore CS1591
        [EnumMember(Value = "IMAGERY_CONTENT_ALCOHOL_GAMBLING_CANNABIS_DRUGS")]
        #pragma warning disable CS1591
        ImageryContentAlcoholGamblingCannabisDrugs,
        #pragma warning restore CS1591
        [EnumMember(Value = "IMPROPER_CERTIFICATION_PHARMA")]
        #pragma warning disable CS1591
        ImproperCertificationPharma,
        #pragma warning restore CS1591
        [EnumMember(Value = "INABILITY_TO_INTERACT")]
        #pragma warning disable CS1591
        InabilityToInteract,
        #pragma warning restore CS1591
        [EnumMember(Value = "INAPPROPRIATE_CONTENT")]
        #pragma warning disable CS1591
        InappropriateContent,
        #pragma warning restore CS1591
        [EnumMember(Value = "INAPPROPRIATE_TARGETING")]
        #pragma warning disable CS1591
        InappropriateTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "INTOLERANT_OR_OVERLY_CONTENTIOUS_CULTURAL_TOPICS")]
        #pragma warning disable CS1591
        IntolerantOrOverlyContentiousCulturalTopics,
        #pragma warning restore CS1591
        [EnumMember(Value = "LANDING_PAGE_LANGUAGE")]
        #pragma warning disable CS1591
        LandingPageLanguage,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIVE_ANIMALS")]
        #pragma warning disable CS1591
        LiveAnimals,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIVE_ANIMALS_AND_ANIMAL_PRODUCTS")]
        #pragma warning disable CS1591
        LiveAnimalsAndAnimalProducts,
        #pragma warning restore CS1591
        [EnumMember(Value = "MATURE_RATED_VIDEO")]
        #pragma warning disable CS1591
        MatureRatedVideo,
        #pragma warning restore CS1591
        [EnumMember(Value = "NSFW_18_PROFILE")]
        #pragma warning disable CS1591
        Nsfw18Profile,
        #pragma warning restore CS1591
        [EnumMember(Value = "NSFW_HASHTAG")]
        #pragma warning disable CS1591
        NsfwHashtag,
        #pragma warning restore CS1591
        [EnumMember(Value = "NSFW_ONLY")]
        #pragma warning disable CS1591
        NsfwOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "NUDITY")]
        #pragma warning disable CS1591
        Nudity,
        #pragma warning restore CS1591
        [EnumMember(Value = "OBSCENE_OFFENSIVE")]
        #pragma warning disable CS1591
        ObsceneOffensive,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAID_FANTASY_SPORTS")]
        #pragma warning disable CS1591
        PaidFantasySports,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERSONAL_INFORMATION")]
        #pragma warning disable CS1591
        PersonalInformation,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHARMACEUTICAL_MEDICAL_PRODUCTS")]
        #pragma warning disable CS1591
        PharmaceuticalMedicalProducts,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICAL_ADS_PROHIBITED")]
        #pragma warning disable CS1591
        PoliticalAdsProhibited,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICAL_ADS_RESTRICTED")]
        #pragma warning disable CS1591
        PoliticalAdsRestricted,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICAL_ADS_UNMANAGED_ADVERTISER")]
        #pragma warning disable CS1591
        PoliticalAdsUnmanagedAdvertiser,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICAL_ADVERTISEMENTS")]
        #pragma warning disable CS1591
        PoliticalAdvertisements,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICAL_ADVERTISEMENTS_NOT_MANAGED_REDDIT")]
        #pragma warning disable CS1591
        PoliticalAdvertisementsNotManagedReddit,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICAL_ADVERTISEMENTS_OUTSIDE_US")]
        #pragma warning disable CS1591
        PoliticalAdvertisementsOutsideUs,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICAL_ADVERTISEMENTS_STATE_LOCAL")]
        #pragma warning disable CS1591
        PoliticalAdvertisementsStateLocal,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICAL_VIDEO")]
        #pragma warning disable CS1591
        PoliticalVideo,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICS_GEO_TARGETING")]
        #pragma warning disable CS1591
        PoliticsGeoTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "PORN_VIDEO")]
        #pragma warning disable CS1591
        PornVideo,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROFANITIES")]
        #pragma warning disable CS1591
        Profanities,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROFANITY")]
        #pragma warning disable CS1591
        Profanity,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROHIBITED_ADVERTISEMENTS")]
        #pragma warning disable CS1591
        ProhibitedAdvertisements,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROHIBITED_PRODUCTS_SERVICES")]
        #pragma warning disable CS1591
        ProhibitedProductsServices,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROHIBITED_TARGETING")]
        #pragma warning disable CS1591
        ProhibitedTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUNCTUATION")]
        #pragma warning disable CS1591
        Punctuation,
        #pragma warning restore CS1591
        [EnumMember(Value = "QUALITY")]
        #pragma warning disable CS1591
        Quality,
        #pragma warning restore CS1591
        [EnumMember(Value = "QUALITY_SINGLE_ARTICLE")]
        #pragma warning disable CS1591
        QualitySingleArticle,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECREATIONAL_DRUGS_ADDICTION_AND_TREATMENT_PROGRAMS")]
        #pragma warning disable CS1591
        RecreationalDrugsAddictionAndTreatmentPrograms,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECREATIONAL_DRUGS_AGE_TARGETING")]
        #pragma warning disable CS1591
        RecreationalDrugsAgeTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECREATIONAL_DRUGS_DIRECT_SALE_OF_CANNABIS_CANADA_ONLY")]
        #pragma warning disable CS1591
        RecreationalDrugsDirectSaleOfCannabisCanadaOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECREATIONAL_DRUGS_DOESNT_MEET_REQUIREMENTS_US_ONLY")]
        #pragma warning disable CS1591
        RecreationalDrugsDoesntMeetRequirementsUsOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECREATIONAL_DRUGS_GEO_TARGETING")]
        #pragma warning disable CS1591
        RecreationalDrugsGeoTargeting,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECREATIONAL_DRUGS_LICENSING_AND_REGISTRATION")]
        #pragma warning disable CS1591
        RecreationalDrugsLicensingAndRegistration,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECREATIONAL_DRUGS_PRICES_AND_OR_DISTRIBUTION_CANADA_ONLY")]
        #pragma warning disable CS1591
        RecreationalDrugsPricesAndOrDistributionCanadaOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECREATIONAL_DRUGS_PROHIBITED_CLAIMS_CANADA_US_ONLY")]
        #pragma warning disable CS1591
        RecreationalDrugsProhibitedClaimsCanadaUsOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECREATIONAL_DRUGS_PROHIBITED_PRODUCTS")]
        #pragma warning disable CS1591
        RecreationalDrugsProhibitedProducts,
        #pragma warning restore CS1591
        [EnumMember(Value = "REDIRECT_URL")]
        #pragma warning disable CS1591
        RedirectUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "REHAB_ADDICTION_CENTERS")]
        #pragma warning disable CS1591
        RehabAddictionCenters,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESALE_OF_EVENT_TICKETS")]
        #pragma warning disable CS1591
        ResaleOfEventTickets,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEXUALLY_EXPLICIT_CONTENT")]
        #pragma warning disable CS1591
        SexuallyExplicitContent,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHORTEN_URL")]
        #pragma warning disable CS1591
        ShortenUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPELLING")]
        #pragma warning disable CS1591
        Spelling,
        #pragma warning restore CS1591
        [EnumMember(Value = "STYLE_POLICIES_GENERAL")]
        #pragma warning disable CS1591
        StylePoliciesGeneral,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUPPLEMENTS")]
        #pragma warning disable CS1591
        Supplements,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUSPENSION")]
        #pragma warning disable CS1591
        Suspension,
        #pragma warning restore CS1591
        [EnumMember(Value = "SYMBOLS_EMOJIS")]
        #pragma warning disable CS1591
        SymbolsEmojis,
        #pragma warning restore CS1591
        [EnumMember(Value = "THIRD_PARTY_RIGHTS")]
        #pragma warning disable CS1591
        ThirdPartyRights,
        #pragma warning restore CS1591
        [EnumMember(Value = "THIRD_PARTY_RIGHTS_MANAGED")]
        #pragma warning disable CS1591
        ThirdPartyRightsManaged,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOBACCO")]
        #pragma warning disable CS1591
        Tobacco,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOBACCO_GENERAL")]
        #pragma warning disable CS1591
        TobaccoGeneral,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRADE_POLICIES")]
        #pragma warning disable CS1591
        TradePolicies,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNOFFICIAL_RESALE_OF_EVENT_TICKETS")]
        #pragma warning disable CS1591
        UnofficialResaleOfEventTickets,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNRELATED_LANDING_PAGE")]
        #pragma warning disable CS1591
        UnrelatedLandingPage,
        #pragma warning restore CS1591
        [EnumMember(Value = "URL_GENERAL")]
        #pragma warning disable CS1591
        UrlGeneral,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERIFY_AUTHORIZED_RESELLER")]
        #pragma warning disable CS1591
        VerifyAuthorizedReseller,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERIFY_AUTHORIZED_TICKET_RESELLER")]
        #pragma warning disable CS1591
        VerifyAuthorizedTicketReseller,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERIFY_ID")]
        #pragma warning disable CS1591
        VerifyId,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIDEO_ADS")]
        #pragma warning disable CS1591
        VideoAds,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEAPONS")]
        #pragma warning disable CS1591
        Weapons,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEAPONS_AND_RELATED_PRODUCTS_GENERAL")]
        #pragma warning disable CS1591
        WeaponsAndRelatedProductsGeneral,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
