// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The image crop type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumImageCropType
    {
        [EnumMember(Value = "MANUAL")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
    }
}
