// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The state of the credit card attachment. Applies only for `SELF_SERVE` funding instruments.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaFundingInstrumentAuthorizeStatus
    {
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVED")]
        #pragma warning disable CS1591
        Approved,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECLINE_RETRYABLE")]
        #pragma warning disable CS1591
        DeclineRetryable,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECLINE_TERMINAL")]
        #pragma warning disable CS1591
        DeclineTerminal,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
