// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>
    /// An overview of how many products were affected and any issues that occurred.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComponentsSchemaCatalogImportSummary : IParsable
    {
        /// <summary>How many products were added.</summary>
        public int? AddedProductsCount { get; private set; }
        /// <summary>How many products were deleted.</summary>
        public int? DeletedProductsCount { get; private set; }
        /// <summary>How many products were rejected as invalid and not imported.</summary>
        public int? InvalidProductsCount { get; private set; }
        /// <summary>The mapping of severity levels and how many products are having this issue.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCatalogImportSummaryIssues? Issues { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCatalogImportSummaryIssues Issues { get; set; }
#endif
        /// <summary>How many products were modified.</summary>
        public int? ModifiedProductsCount { get; private set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCatalogImportSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCatalogImportSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCatalogImportSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "added_products_count", n => { AddedProductsCount = n.GetIntValue(); } },
                { "deleted_products_count", n => { DeletedProductsCount = n.GetIntValue(); } },
                { "invalid_products_count", n => { InvalidProductsCount = n.GetIntValue(); } },
                { "issues", n => { Issues = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCatalogImportSummaryIssues>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCatalogImportSummaryIssues.CreateFromDiscriminatorValue); } },
                { "modified_products_count", n => { ModifiedProductsCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCatalogImportSummaryIssues>("issues", Issues);
        }
    }
}
#pragma warning restore CS0618
