// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The catalog&apos;s data source.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaProductCatalogDataSourcesItem
    {
        [EnumMember(Value = "BULK_IMPORT")]
        #pragma warning disable CS1591
        BulkImport,
        #pragma warning restore CS1591
        [EnumMember(Value = "FEED_SYNC")]
        #pragma warning disable CS1591
        FeedSync,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANUAL")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
    }
}
