// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaAdAccount : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Describes the state of the account. Can only be changed by Reddit.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAdminApproval? AdminApproval { get; set; }
        /// <summary>The attribution type for app install campaigns.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppAttributionType? AppAttributionType { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppAttributionType AppAttributionType { get; set; }
#endif
        /// <summary>The window for app install click attribution. Used for reporting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppClickAttributionWindow? AppClickAttributionWindow { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppClickAttributionWindow AppClickAttributionWindow { get; set; }
#endif
        /// <summary>The window for app install view attribution. Used for reporting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppViewAttributionWindow? AppViewAttributionWindow { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppViewAttributionWindow AppViewAttributionWindow { get; set; }
#endif
        /// <summary>The attribution conversion type. Valid for cost-per-action (CPA) bid types. Also configures the attribution type to query when calculating effective-cost-per-action (eCPA) fields.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsAttributionType? AttributionType { get; set; }
        /// <summary>The business ID.</summary>
        public Guid? BusinessId { get; set; }
        /// <summary>The window for click attributions. Used for reporting.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountClickAttributionWindow? ClickAttributionWindow { get; set; }
        /// <summary>When this entity was created ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountCurrency? Currency { get; private set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountCurrency Currency { get; private set; }
#endif
        /// <summary>The communities (&quot;subreddits&quot;) excluded at the ad account level. Ads won&apos;t be eligible for auctions in these communities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludedCommunities { get; set; }
#nullable restore
#else
        public List<string> ExcludedCommunities { get; set; }
#endif
        /// <summary>The keywords excluded at the ad account level. Ads won&apos;t be eligible for auctions if they contain these keywords.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludedKeywords { get; set; }
#nullable restore
#else
        public List<string> ExcludedKeywords { get; set; }
#endif
        /// <summary>The ad account ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; private set; }
#nullable restore
#else
        public string Id { get; private set; }
#endif
        /// <summary>When this entity was last changed ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>The entity name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Pixel partners allowed by the advertiser.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountPixelPartnerPreferencesItem?>? PixelPartnerPreferences { get; private set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountPixelPartnerPreferencesItem?> PixelPartnerPreferences { get; private set; }
#endif
        /// <summary>The primary contact member&apos;s ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryContactMemberId { get; set; }
#nullable restore
#else
        public string PrimaryContactMemberId { get; set; }
#endif
        /// <summary>The spend cap period applied to the ad account.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountSpendCapType? SpendCapType { get; set; }
        /// <summary>Why this ad account was suspended.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountSuspensionReason? SuspensionReason { get; private set; }
        /// <summary>The time_zone_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZoneId { get; private set; }
#nullable restore
#else
        public string TimeZoneId { get; private set; }
#endif
        /// <summary>The ad account type. Can only be changed by Reddit.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountType? Type { get; set; }
        /// <summary>The window for view attributions. Used in reporting.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountViewAttributionWindow? ViewAttributionWindow { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccount"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccount CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccount();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "admin_approval", n => { AdminApproval = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAdminApproval>(); } },
                { "app_attribution_type", n => { AppAttributionType = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppAttributionType>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppAttributionType.CreateFromDiscriminatorValue); } },
                { "app_click_attribution_window", n => { AppClickAttributionWindow = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppClickAttributionWindow>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppClickAttributionWindow.CreateFromDiscriminatorValue); } },
                { "app_view_attribution_window", n => { AppViewAttributionWindow = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppViewAttributionWindow>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppViewAttributionWindow.CreateFromDiscriminatorValue); } },
                { "attribution_type", n => { AttributionType = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsAttributionType>(); } },
                { "business_id", n => { BusinessId = n.GetGuidValue(); } },
                { "click_attribution_window", n => { ClickAttributionWindow = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountClickAttributionWindow>(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency", n => { Currency = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountCurrency>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountCurrency.CreateFromDiscriminatorValue); } },
                { "excluded_communities", n => { ExcludedCommunities = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "excluded_keywords", n => { ExcludedKeywords = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "modified_at", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "pixel_partner_preferences", n => { PixelPartnerPreferences = n.GetCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountPixelPartnerPreferencesItem>()?.AsList(); } },
                { "primary_contact_member_id", n => { PrimaryContactMemberId = n.GetStringValue(); } },
                { "spend_cap_type", n => { SpendCapType = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountSpendCapType>(); } },
                { "suspension_reason", n => { SuspensionReason = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountSuspensionReason>(); } },
                { "time_zone_id", n => { TimeZoneId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountType>(); } },
                { "view_attribution_window", n => { ViewAttributionWindow = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountViewAttributionWindow>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAdminApproval>("admin_approval", AdminApproval);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppAttributionType>("app_attribution_type", AppAttributionType);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppClickAttributionWindow>("app_click_attribution_window", AppClickAttributionWindow);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountAppViewAttributionWindow>("app_view_attribution_window", AppViewAttributionWindow);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsAttributionType>("attribution_type", AttributionType);
            writer.WriteGuidValue("business_id", BusinessId);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountClickAttributionWindow>("click_attribution_window", ClickAttributionWindow);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteCollectionOfPrimitiveValues<string>("excluded_communities", ExcludedCommunities);
            writer.WriteCollectionOfPrimitiveValues<string>("excluded_keywords", ExcludedKeywords);
            writer.WriteDateTimeOffsetValue("modified_at", ModifiedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("primary_contact_member_id", PrimaryContactMemberId);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountSpendCapType>("spend_cap_type", SpendCapType);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountType>("type", Type);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdAccountViewAttributionWindow>("view_attribution_window", ViewAttributionWindow);
        }
    }
}
#pragma warning restore CS0618
