// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The issue code encountered in the catalog import.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumsCatalogImportIssueCode
    {
        [EnumMember(Value = "INTERNAL_ERROR")]
        #pragma warning disable CS1591
        InternalError,
        #pragma warning restore CS1591
        [EnumMember(Value = "FETCH_ERROR")]
        #pragma warning disable CS1591
        FetchError,
        #pragma warning restore CS1591
        [EnumMember(Value = "FILE_NOT_FOUND")]
        #pragma warning disable CS1591
        FileNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_FEED_URL")]
        #pragma warning disable CS1591
        InvalidFeedUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNAUTHORIZED_ERROR")]
        #pragma warning disable CS1591
        UnauthorizedError,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_FILE_FORMAT")]
        #pragma warning disable CS1591
        InvalidFileFormat,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_FILE_ENCODING")]
        #pragma warning disable CS1591
        InvalidFileEncoding,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_FILE_HEADER")]
        #pragma warning disable CS1591
        InvalidFileHeader,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_LINE_FORMAT")]
        #pragma warning disable CS1591
        InvalidLineFormat,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_DELIMITER")]
        #pragma warning disable CS1591
        InvalidDelimiter,
        #pragma warning restore CS1591
        [EnumMember(Value = "INCORRECT_PRODUCTS_COUNT")]
        #pragma warning disable CS1591
        IncorrectProductsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_PRODUCT_ID")]
        #pragma warning disable CS1591
        MissingProductId,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_TITLE")]
        #pragma warning disable CS1591
        MissingTitle,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_DESCRIPTION")]
        #pragma warning disable CS1591
        MissingDescription,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_LINK")]
        #pragma warning disable CS1591
        MissingLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_IMAGE_LINK")]
        #pragma warning disable CS1591
        MissingImageLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_PRICE")]
        #pragma warning disable CS1591
        MissingPrice,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_PRODUCT_ID")]
        #pragma warning disable CS1591
        InvalidProductId,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_TITLE")]
        #pragma warning disable CS1591
        InvalidTitle,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_DESCRIPTION")]
        #pragma warning disable CS1591
        InvalidDescription,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_LINK")]
        #pragma warning disable CS1591
        InvalidLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_IMAGE_LINK")]
        #pragma warning disable CS1591
        InvalidImageLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_PRICE")]
        #pragma warning disable CS1591
        InvalidPrice,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_ITEM_GROUP_ID")]
        #pragma warning disable CS1591
        InvalidItemGroupId,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_ADDITIONAL_IMAGE_LINKS")]
        #pragma warning disable CS1591
        InvalidAdditionalImageLinks,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_MOBILE_LINK")]
        #pragma warning disable CS1591
        InvalidMobileLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_SALE_PRICE")]
        #pragma warning disable CS1591
        InvalidSalePrice,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_PRODUCT_TYPE")]
        #pragma warning disable CS1591
        InvalidProductType,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_COLOR")]
        #pragma warning disable CS1591
        InvalidColor,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CUSTOM_LABEL_0")]
        #pragma warning disable CS1591
        InvalidCustomLabel0,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CUSTOM_LABEL_1")]
        #pragma warning disable CS1591
        InvalidCustomLabel1,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CUSTOM_LABEL_2")]
        #pragma warning disable CS1591
        InvalidCustomLabel2,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CUSTOM_LABEL_3")]
        #pragma warning disable CS1591
        InvalidCustomLabel3,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CUSTOM_LABEL_4")]
        #pragma warning disable CS1591
        InvalidCustomLabel4,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_SALE_PRICE_EFFECTIVE_DATE")]
        #pragma warning disable CS1591
        InvalidSalePriceEffectiveDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_EXPIRATION_DATE")]
        #pragma warning disable CS1591
        InvalidExpirationDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_ADULT")]
        #pragma warning disable CS1591
        InvalidAdult,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_AGE_GROUP")]
        #pragma warning disable CS1591
        InvalidAgeGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_GENDER")]
        #pragma warning disable CS1591
        InvalidGender,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_MATERIAL")]
        #pragma warning disable CS1591
        InvalidMaterial,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_PATTERN")]
        #pragma warning disable CS1591
        InvalidPattern,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_SIZE")]
        #pragma warning disable CS1591
        InvalidSize,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_SIZE_TYPE")]
        #pragma warning disable CS1591
        InvalidSizeType,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_BRAND")]
        #pragma warning disable CS1591
        InvalidBrand,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CONDITION")]
        #pragma warning disable CS1591
        InvalidCondition,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_GTIN")]
        #pragma warning disable CS1591
        InvalidGtin,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_MPN")]
        #pragma warning disable CS1591
        InvalidMpn,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_AVAILABILITY")]
        #pragma warning disable CS1591
        InvalidAvailability,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_AVERAGE_REVIEW_RATING")]
        #pragma warning disable CS1591
        InvalidAverageReviewRating,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_COST_OF_GOODS_SOLD")]
        #pragma warning disable CS1591
        InvalidCostOfGoodsSold,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CUSTOM_NUMBER_0")]
        #pragma warning disable CS1591
        InvalidCustomNumber0,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CUSTOM_NUMBER_1")]
        #pragma warning disable CS1591
        InvalidCustomNumber1,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CUSTOM_NUMBER_2")]
        #pragma warning disable CS1591
        InvalidCustomNumber2,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CUSTOM_NUMBER_3")]
        #pragma warning disable CS1591
        InvalidCustomNumber3,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CUSTOM_NUMBER_4")]
        #pragma warning disable CS1591
        InvalidCustomNumber4,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_GOOGLE_PRODUCT_CATEGORY")]
        #pragma warning disable CS1591
        InvalidGoogleProductCategory,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_IS_BUNDLE")]
        #pragma warning disable CS1591
        InvalidIsBundle,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_LIFESTYLE_IMAGE_LINK")]
        #pragma warning disable CS1591
        InvalidLifestyleImageLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_NUMBER_OF_RATINGS")]
        #pragma warning disable CS1591
        InvalidNumberOfRatings,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_PLATFORM_SPECIFIC_LINK")]
        #pragma warning disable CS1591
        InvalidPlatformSpecificLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_PRODUCT_DETAIL")]
        #pragma warning disable CS1591
        InvalidProductDetail,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_PRODUCT_HIGHLIGHT")]
        #pragma warning disable CS1591
        InvalidProductHighlight,
        #pragma warning restore CS1591
        [EnumMember(Value = "INCOMPATIBLE_WITH_FUTURE_RELEASE")]
        #pragma warning disable CS1591
        IncompatibleWithFutureRelease,
        #pragma warning restore CS1591
    }
}
