// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ComponentsEnumsCustomAudienceSupportedSchemasItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "EMAIL_SHA256")]
        #pragma warning disable CS1591
        EmailSha256,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAID_SHA256")]
        #pragma warning disable CS1591
        MaidSha256,
        #pragma warning restore CS1591
    }
}
