// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The type of source for conversion events.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumActionSource
    {
        [EnumMember(Value = "WEBSITE")]
        #pragma warning disable CS1591
        Website,
        #pragma warning restore CS1591
        [EnumMember(Value = "APP")]
        #pragma warning disable CS1591
        App,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHYSICAL_STORE")]
        #pragma warning disable CS1591
        PhysicalStore,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
    }
}
