// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaLastFiredAtReport : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The last time `AddToCart` was fired.</summary>
        public DateTimeOffset? AddToCart { get; set; }
        /// <summary>The last time `AddToWishlist` was fired.</summary>
        public DateTimeOffset? AddToWishlist { get; set; }
        /// <summary>The most recent time each custom conversion event was fired.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReportBreakdownProperty? Breakdown { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReportBreakdownProperty Breakdown { get; set; }
#endif
        /// <summary>The last time a custom conversion event was fired.</summary>
        public DateTimeOffset? Custom { get; set; }
        /// <summary>A list of recently-fired custom conversion events and their timestamps.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReportCustomEventsItem>? CustomEvents { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReportCustomEventsItem> CustomEvents { get; set; }
#endif
        /// <summary>The last time `Lead` was fired.</summary>
        public DateTimeOffset? Lead { get; set; }
        /// <summary>The last time `PageVisit` was fired.</summary>
        public DateTimeOffset? PageVisit { get; set; }
        /// <summary>The last time `Purchase` was fired.</summary>
        public DateTimeOffset? Purchase { get; set; }
        /// <summary>The last time `Search` was fired.</summary>
        public DateTimeOffset? Search { get; set; }
        /// <summary>The last time `SignUp` was fired.</summary>
        public DateTimeOffset? SignUp { get; set; }
        /// <summary>The last time `ViewContent` was fired.</summary>
        public DateTimeOffset? ViewContent { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReport"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReport CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReport();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_to_cart", n => { AddToCart = n.GetDateTimeOffsetValue(); } },
                { "add_to_wishlist", n => { AddToWishlist = n.GetDateTimeOffsetValue(); } },
                { "breakdown", n => { Breakdown = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReportBreakdownProperty>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReportBreakdownProperty.CreateFromDiscriminatorValue); } },
                { "custom", n => { Custom = n.GetDateTimeOffsetValue(); } },
                { "custom_events", n => { CustomEvents = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReportCustomEventsItem>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReportCustomEventsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lead", n => { Lead = n.GetDateTimeOffsetValue(); } },
                { "page_visit", n => { PageVisit = n.GetDateTimeOffsetValue(); } },
                { "purchase", n => { Purchase = n.GetDateTimeOffsetValue(); } },
                { "search", n => { Search = n.GetDateTimeOffsetValue(); } },
                { "sign_up", n => { SignUp = n.GetDateTimeOffsetValue(); } },
                { "view_content", n => { ViewContent = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("add_to_cart", AddToCart);
            writer.WriteDateTimeOffsetValue("add_to_wishlist", AddToWishlist);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReportBreakdownProperty>("breakdown", Breakdown);
            writer.WriteDateTimeOffsetValue("custom", Custom);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaLastFiredAtReportCustomEventsItem>("custom_events", CustomEvents);
            writer.WriteDateTimeOffsetValue("lead", Lead);
            writer.WriteDateTimeOffsetValue("page_visit", PageVisit);
            writer.WriteDateTimeOffsetValue("purchase", Purchase);
            writer.WriteDateTimeOffsetValue("search", Search);
            writer.WriteDateTimeOffsetValue("sign_up", SignUp);
            writer.WriteDateTimeOffsetValue("view_content", ViewContent);
        }
    }
}
#pragma warning restore CS0618
