// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The [SKAdNetwork source ID status](https://business.reddithelp.com/s/article/skadnetwork#skan-ids).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaSkadnetworkMetadataStatus
    {
        [EnumMember(Value = "COOLDOWN")]
        #pragma warning disable CS1591
        Cooldown,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISABLED")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENABLED")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
    }
}
