// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaPostContentItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The call to action text.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsCallToAction? CallToAction { get; set; }
        /// <summary>A carousel image&apos;s caption.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Caption { get; set; }
#nullable restore
#else
        public string Caption { get; set; }
#endif
        /// <summary>The URL to navigate users to on click. Required for image and carousel posts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationUrl { get; set; }
#nullable restore
#else
        public string DestinationUrl { get; set; }
#endif
        /// <summary>Shows instead of the destination URL. Must match the destination URL domain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayUrl { get; set; }
#nullable restore
#else
        public string DisplayUrl { get; set; }
#endif
        /// <summary>The post&apos;s media URL. Required for image, video and carousel posts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaUrl { get; set; }
#nullable restore
#else
        public string MediaUrl { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostContentItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostContentItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostContentItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "call_to_action", n => { CallToAction = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsCallToAction>(); } },
                { "caption", n => { Caption = n.GetStringValue(); } },
                { "destination_url", n => { DestinationUrl = n.GetStringValue(); } },
                { "display_url", n => { DisplayUrl = n.GetStringValue(); } },
                { "media_url", n => { MediaUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsCallToAction>("call_to_action", CallToAction);
            writer.WriteStringValue("caption", Caption);
            writer.WriteStringValue("destination_url", DestinationUrl);
            writer.WriteStringValue("display_url", DisplayUrl);
            writer.WriteStringValue("media_url", MediaUrl);
        }
    }
}
#pragma warning restore CS0618
