// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The audience&apos;s data provider.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaThirdPartyDataCostPartner
    {
        [EnumMember(Value = "LIVE_RAMP")]
        #pragma warning disable CS1591
        LiveRamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "BOMBORA")]
        #pragma warning disable CS1591
        Bombora,
        #pragma warning restore CS1591
    }
}
