// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaTimeBlock : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Day of the week when this window ends (`0`–`6`; `0` = Sunday).</summary>
        public int? EndDay { get; set; }
        /// <summary>Hour on `end_day` when this window ends (`0`–`23`).</summary>
        public int? EndHour { get; set; }
        /// <summary>Day of the week when this window starts (`0`–`6`; `0` = Sunday).</summary>
        public int? StartDay { get; set; }
        /// <summary>Hour on `start_day` when this window starts (`0`–`23`).</summary>
        public int? StartHour { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTimeBlock"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTimeBlock CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTimeBlock();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end_day", n => { EndDay = n.GetIntValue(); } },
                { "end_hour", n => { EndHour = n.GetIntValue(); } },
                { "start_day", n => { StartDay = n.GetIntValue(); } },
                { "start_hour", n => { StartHour = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("end_day", EndDay);
            writer.WriteIntValue("end_hour", EndHour);
            writer.WriteIntValue("start_day", StartDay);
            writer.WriteIntValue("start_hour", StartHour);
        }
    }
}
#pragma warning restore CS0618
