// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaTargeting : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The [mobile carriers](https://ads-api.reddit.com/docs/v3/operations/List%20Carriers) to target.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingCarriersItem?>? Carriers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingCarriersItem?> Carriers { get; set; }
#endif
        /// <summary>The [Reddit communities (&quot;subreddits&quot;)](https://ads-api.reddit.com/docs/v3/operations/List%20Communities) to target.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Communities { get; set; }
#nullable restore
#else
        public List<string> Communities { get; set; }
#endif
        /// <summary>The [custom audiences](https://ads-api.reddit.com/docs/v3/operations/List%20User%20Custom%20Audiences) to target.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomAudienceIds { get; set; }
#nullable restore
#else
        public List<string> CustomAudienceIds { get; set; }
#endif
        /// <summary>The [devices](https://ads-api.reddit.com/docs/v3/operations/List%20Devices) to target. Exactly one device must be targeted for `APP_INSTALLS` campaigns.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeviceTarget>? Devices { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeviceTarget> Devices { get; set; }
#endif
        /// <summary>The communities (&quot;subreddits&quot;) to exclude from targeting. Ads won&apos;t be eligible for auctions in these communities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludedCommunities { get; set; }
#nullable restore
#else
        public List<string> ExcludedCommunities { get; set; }
#endif
        /// <summary>The custom audiences to exclude from targeting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludedCustomAudienceIds { get; set; }
#nullable restore
#else
        public List<string> ExcludedCustomAudienceIds { get; set; }
#endif
        /// <summary>The geolocations to exclude from targeting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludedGeolocations { get; set; }
#nullable restore
#else
        public List<string> ExcludedGeolocations { get; set; }
#endif
        /// <summary>The interests to exclude from targeting.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludedInterests { get; set; }
#nullable restore
#else
        public List<string> ExcludedInterests { get; set; }
#endif
        /// <summary>The keywords to exclude from targeting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludedKeywords { get; set; }
#nullable restore
#else
        public List<string> ExcludedKeywords { get; set; }
#endif
        /// <summary>Allow Reddit to expand your targeting options. Learn about [automated targeting](https://business.reddithelp.com/s/article/automated-targeting).</summary>
        public bool? ExpandTargeting { get; set; }
        /// <summary>The gender group to target.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingGender? Gender { get; set; }
        /// <summary>The [geolocations](https://ads-api.reddit.com/docs/v3/operations/List%20Geolocations) to target.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Geolocations { get; set; }
#nullable restore
#else
        public List<string> Geolocations { get; set; }
#endif
        /// <summary>The [interests](https://ads-api.reddit.com/docs/v3/operations/List%20Interests) to target.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Interests { get; set; }
#nullable restore
#else
        public List<string> Interests { get; set; }
#endif
        /// <summary>The keywords to target.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Keywords { get; set; }
#nullable restore
#else
        public List<string> Keywords { get; set; }
#endif
        /// <summary>The [languages](https://ads-api.reddit.com/docs/v3/operations/List%20Languages) to target ([ISO 639-1](https://www.loc.gov/standards/iso639-2/php/code_list.php)).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumTargetingLanguageCodes?>? Languages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumTargetingLanguageCodes?> Languages { get; set; }
#endif
        /// <summary>The client location to place the advertisement. For collections ads, only `FEED` is supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsPlacements?>? Locations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsPlacements?> Locations { get; set; }
#endif
        /// <summary>The platforms to show the advertisement on. At least 1 mobile type must be targeted for `APP_INSTALLS` campaigns.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingPlatformsItem?>? Platforms { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingPlatformsItem?> Platforms { get; set; }
#endif
        /// <summary>The suppression event types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.AllFeaturesItem?>? SuppressionEventTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.AllFeaturesItem?> SuppressionEventTypes { get; set; }
#endif
        /// <summary>The layouts the ad can be placed in.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingViewModesItem?>? ViewModes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingViewModesItem?> ViewModes { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargeting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargeting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargeting();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "carriers", n => { Carriers = n.GetCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingCarriersItem>()?.AsList(); } },
                { "communities", n => { Communities = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "custom_audience_ids", n => { CustomAudienceIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "devices", n => { Devices = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeviceTarget>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeviceTarget.CreateFromDiscriminatorValue)?.AsList(); } },
                { "excluded_communities", n => { ExcludedCommunities = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "excluded_custom_audience_ids", n => { ExcludedCustomAudienceIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "excluded_geolocations", n => { ExcludedGeolocations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "excluded_interests", n => { ExcludedInterests = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "excluded_keywords", n => { ExcludedKeywords = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "expand_targeting", n => { ExpandTargeting = n.GetBoolValue(); } },
                { "gender", n => { Gender = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingGender>(); } },
                { "geolocations", n => { Geolocations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "interests", n => { Interests = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "keywords", n => { Keywords = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "languages", n => { Languages = n.GetCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumTargetingLanguageCodes>()?.AsList(); } },
                { "locations", n => { Locations = n.GetCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsPlacements>()?.AsList(); } },
                { "platforms", n => { Platforms = n.GetCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingPlatformsItem>()?.AsList(); } },
                { "suppression_event_types", n => { SuppressionEventTypes = n.GetCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.AllFeaturesItem>()?.AsList(); } },
                { "view_modes", n => { ViewModes = n.GetCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingViewModesItem>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingCarriersItem>("carriers", Carriers);
            writer.WriteCollectionOfPrimitiveValues<string>("communities", Communities);
            writer.WriteCollectionOfPrimitiveValues<string>("custom_audience_ids", CustomAudienceIds);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaDeviceTarget>("devices", Devices);
            writer.WriteCollectionOfPrimitiveValues<string>("excluded_communities", ExcludedCommunities);
            writer.WriteCollectionOfPrimitiveValues<string>("excluded_custom_audience_ids", ExcludedCustomAudienceIds);
            writer.WriteCollectionOfPrimitiveValues<string>("excluded_geolocations", ExcludedGeolocations);
            writer.WriteCollectionOfPrimitiveValues<string>("excluded_interests", ExcludedInterests);
            writer.WriteCollectionOfPrimitiveValues<string>("excluded_keywords", ExcludedKeywords);
            writer.WriteBoolValue("expand_targeting", ExpandTargeting);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingGender>("gender", Gender);
            writer.WriteCollectionOfPrimitiveValues<string>("geolocations", Geolocations);
            writer.WriteCollectionOfPrimitiveValues<string>("interests", Interests);
            writer.WriteCollectionOfPrimitiveValues<string>("keywords", Keywords);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumTargetingLanguageCodes>("languages", Languages);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsPlacements>("locations", Locations);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingPlatformsItem>("platforms", Platforms);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.AllFeaturesItem>("suppression_event_types", SuppressionEventTypes);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargetingViewModesItem>("view_modes", ViewModes);
        }
    }
}
#pragma warning restore CS0618
