// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The type of conversion event for an ad. Only used for shopping ads targeting.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumsConversionEventType
    {
        [EnumMember(Value = "ADD_TO_CART")]
        #pragma warning disable CS1591
        AddToCart,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADD_TO_WISHLIST")]
        #pragma warning disable CS1591
        AddToWishlist,
        #pragma warning restore CS1591
        [EnumMember(Value = "PURCHASE")]
        #pragma warning disable CS1591
        Purchase,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEARCH")]
        #pragma warning disable CS1591
        Search,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIEW_CONTENT")]
        #pragma warning disable CS1591
        ViewContent,
        #pragma warning restore CS1591
    }
}
