// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The upload processing status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsSchemaFinishedCreativeAssetUploadStatus
    {
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_MEDIA")]
        #pragma warning disable CS1591
        InvalidMedia,
        #pragma warning restore CS1591
    }
}
