// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The type of view-through conversion being measured. For ad groups under CBO campaigns, this field must match the campaign&apos;s `view_through_conversion_type`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumsViewThroughConversionType
    {
        [EnumMember(Value = "SEVEN_DAY_CLICKS")]
        #pragma warning disable CS1591
        SevenDayClicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEVEN_DAY_CLICKS_ONE_DAY_VIEW")]
        #pragma warning disable CS1591
        SevenDayClicksOneDayView,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
