// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaCustomerListCustomAudience : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ID of the ad account that owns this custom audience.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdAccountId { get; set; }
#nullable restore
#else
        public string AdAccountId { get; set; }
#endif
        /// <summary>The ID of the business that owns this custom audience.</summary>
        public Guid? BusinessId { get; private set; }
        /// <summary>The cost information for audiences using third-party data providers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.Cost? Cost { get; private set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.Cost Cost { get; private set; }
#endif
        /// <summary>When this entity was created ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Details for the [customer list audience](https://business.reddithelp.com/s/article/custom-audiences#customer-lists).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListConfig? CustomerListConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListConfig CustomerListConfig { get; set; }
#endif
        /// <summary>The delivery statuses for this ad group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DeliveryStatus { get; private set; }
#nullable restore
#else
        public List<string> DeliveryStatus { get; private set; }
#endif
        /// <summary>The custom audience ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>When this entity was last changed ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The lower bound of the estimated matched users for this audience.</summary>
        public int? SizeRangeLower { get; set; }
        /// <summary>The upper bound of the estimated matched users for this audience.</summary>
        public int? SizeRangeUpper { get; set; }
        /// <summary>The custom audience&apos;s processing status.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.Status? Status { get; private set; }
        /// <summary>The custom audience type, which must be `CUSTOMER_LIST`.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.CustomerListType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListCustomAudience"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListCustomAudience CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListCustomAudience();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ad_account_id", n => { AdAccountId = n.GetStringValue(); } },
                { "business_id", n => { BusinessId = n.GetGuidValue(); } },
                { "cost", n => { Cost = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.Cost>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.Cost.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "customer_list_config", n => { CustomerListConfig = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListConfig>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListConfig.CreateFromDiscriminatorValue); } },
                { "delivery_status", n => { DeliveryStatus = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "modified_at", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "size_range_lower", n => { SizeRangeLower = n.GetIntValue(); } },
                { "size_range_upper", n => { SizeRangeUpper = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.Status>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.CustomerListType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ad_account_id", AdAccountId);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListConfig>("customer_list_config", CustomerListConfig);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("modified_at", ModifiedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("size_range_lower", SizeRangeLower);
            writer.WriteIntValue("size_range_upper", SizeRangeUpper);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.CustomerListType>("type", Type);
        }
    }
}
#pragma warning restore CS0618
