// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The text format.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumsTextFormat
    {
        [EnumMember(Value = "PLAIN_TEXT")]
        #pragma warning disable CS1591
        PlainText,
        #pragma warning restore CS1591
        [EnumMember(Value = "RICH_TEXT_JSON")]
        #pragma warning disable CS1591
        RichTextJson,
        #pragma warning restore CS1591
    }
}
