// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComponentsSchemaBidSuggestion : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The maximum suggested bid value (microcurrency).</summary>
        public int? BidSuggestionMax { get; set; }
        /// <summary>The median suggested bid value (microcurrency).</summary>
        public int? BidSuggestionMedian { get; set; }
        /// <summary>The minimum suggested bid value (microcurrency).</summary>
        public int? BidSuggestionMin { get; set; }
        /// <summary>The absolute minimum bid value (microcurrency). Bids below this value will be rejected.</summary>
        public int? MinBidValue { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaBidSuggestion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaBidSuggestion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaBidSuggestion();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bid_suggestion_max", n => { BidSuggestionMax = n.GetIntValue(); } },
                { "bid_suggestion_median", n => { BidSuggestionMedian = n.GetIntValue(); } },
                { "bid_suggestion_min", n => { BidSuggestionMin = n.GetIntValue(); } },
                { "min_bid_value", n => { MinBidValue = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bid_suggestion_max", BidSuggestionMax);
            writer.WriteIntValue("bid_suggestion_median", BidSuggestionMedian);
            writer.WriteIntValue("bid_suggestion_min", BidSuggestionMin);
            writer.WriteIntValue("min_bid_value", MinBidValue);
        }
    }
}
#pragma warning restore CS0618
