// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The metric (&quot;tracking type&quot;) to return for a name-keyed conversion custom event.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumConversionCustomEventMetricType
    {
        [EnumMember(Value = "VIEWS")]
        #pragma warning disable CS1591
        Views,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLICKS")]
        #pragma warning disable CS1591
        Clicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "ECPA")]
        #pragma warning disable CS1591
        Ecpa,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOTAL_VALUE")]
        #pragma warning disable CS1591
        TotalValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOTAL_ITEMS")]
        #pragma warning disable CS1591
        TotalItems,
        #pragma warning restore CS1591
        [EnumMember(Value = "AVG_VALUE")]
        #pragma warning disable CS1591
        AvgValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROAS")]
        #pragma warning disable CS1591
        Roas,
        #pragma warning restore CS1591
    }
}
