// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The user&apos;s role in a business. Used to filter businesses by the user&apos;s role.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumsBusinessRole
    {
        [EnumMember(Value = "BUSINESS_ADMIN")]
        #pragma warning disable CS1591
        BusinessAdmin,
        #pragma warning restore CS1591
        [EnumMember(Value = "CATALOG_ADMIN")]
        #pragma warning disable CS1591
        CatalogAdmin,
        #pragma warning restore CS1591
    }
}
