// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The currency used in this invoice ([ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumsBillingCurrency
    {
        [EnumMember(Value = "USD")]
        #pragma warning disable CS1591
        Usd,
        #pragma warning restore CS1591
        [EnumMember(Value = "GBP")]
        #pragma warning disable CS1591
        Gbp,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAD")]
        #pragma warning disable CS1591
        Cad,
        #pragma warning restore CS1591
        [EnumMember(Value = "EUR")]
        #pragma warning disable CS1591
        Eur,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUD")]
        #pragma warning disable CS1591
        Aud,
        #pragma warning restore CS1591
        [EnumMember(Value = "NZD")]
        #pragma warning disable CS1591
        Nzd,
        #pragma warning restore CS1591
        [EnumMember(Value = "SGD")]
        #pragma warning disable CS1591
        Sgd,
        #pragma warning restore CS1591
        [EnumMember(Value = "BRL")]
        #pragma warning disable CS1591
        Brl,
        #pragma warning restore CS1591
    }
}
