// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ComponentsSchemaEngagementAudienceConfigTrackingTypesItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "IMPRESSIONS")]
        #pragma warning disable CS1591
        Impressions,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLICKS")]
        #pragma warning disable CS1591
        Clicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPVOTES")]
        #pragma warning disable CS1591
        Upvotes,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMMENT_SUBMISSIONS")]
        #pragma warning disable CS1591
        CommentSubmissions,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIDEO_WATCHED_50_PERCENT")]
        #pragma warning disable CS1591
        VideoWatched50Percent,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIDEO_WATCHED_100_PERCENT")]
        #pragma warning disable CS1591
        VideoWatched100Percent,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIDEO_STARTED")]
        #pragma warning disable CS1591
        VideoStarted,
        #pragma warning restore CS1591
    }
}
