// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>User identifier type for data deletion.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumsDataDeletionIdentifierType
    {
        [EnumMember(Value = "EMAIL")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHONE_NUMBER")]
        #pragma warning disable CS1591
        PhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "IDFA")]
        #pragma warning disable CS1591
        Idfa,
        #pragma warning restore CS1591
        [EnumMember(Value = "AAID")]
        #pragma warning disable CS1591
        Aaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXTERNAL_ID")]
        #pragma warning disable CS1591
        ExternalId,
        #pragma warning restore CS1591
    }
}
