// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>
    /// Partial ad update. The ad type is immutable. Existing clients may continue sending a matching `type`, but new integrations should omit it.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComponentsSchemaAdPatch : IParsable
    {
        /// <summary>The ad_account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdAccountId { get; set; }
#nullable restore
#else
        public string AdAccountId { get; set; }
#endif
        /// <summary>The ID of the ad group this ad belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdGroupId { get; set; }
#nullable restore
#else
        public string AdGroupId { get; set; }
#endif
        /// <summary>Creative asset identifiers for a Reddit Max template ad. Supply at least 3 distinct headline assets and 2 distinct media assets. The service validates asset ownership, type, status, and version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>? AssetIdentifiers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId> AssetIdentifiers { get; set; }
#endif
        /// <summary>The ID of the ad&apos;s campaign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignId { get; set; }
#nullable restore
#else
        public string CampaignId { get; set; }
#endif
        /// <summary>The [campaign objective](https://business.reddithelp.com/s/article/Ad-campaign-objectives).</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.CampaignObjectiveType2? CampaignObjectiveType { get; set; }
        /// <summary>The URL users are directed to when they click the ad. When `shopping_creative` is set (catalog/product ads), `click_url` is not used for ad delivery; if both are sent in create or update requests, `click_url` is ignored.&gt; **Important:** Updating an ad or creative may update `destination_url`, which `click_url` often needs to match. [Update `click_url` to match its value](/docs/v3/guides/programs/campaign/match-destination-and-click-url) for **image**, **carousel**, or **video** formats.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClickUrl { get; set; }
#nullable restore
#else
        public string ClickUrl { get; set; }
#endif
        /// <summary>Optional query parameters to be appended to the `click_url`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter>? ClickUrlQueryParameters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter> ClickUrlQueryParameters { get; set; }
#endif
        /// <summary>The ad&apos;s status set by the ad account. Can differ from `effective_status` depending on context, such as pending billing information.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ConfiguredStatus2? ConfiguredStatus { get; set; }
        /// <summary>When this entity was created ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The delivery statuses for this ad group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DeliveryStatus { get; private set; }
#nullable restore
#else
        public List<string> DeliveryStatus { get; private set; }
#endif
        /// <summary>The destination for a template ad. Reddit Max template ads do not support a call-to-action value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdPatchDestination? Destination { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdPatchDestination Destination { get; set; }
#endif
        /// <summary>The calculated status determining the real status of this entity.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.EffectiveStatus2? EffectiveStatus { get; private set; }
        /// <summary>Details about enhancements associated with the creative.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesEnhancements? Enhancements { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesEnhancements Enhancements { get; set; }
#endif
        /// <summary>URLs to be called on certain events. Only URLs from Reddit&apos;s list of [approved measurement providers](https://business.reddithelp.com/s/article/Set-up-third-party-measurement) are allowed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem>? EventTrackers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem> EventTrackers { get; set; }
#endif
        /// <summary>The ad ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>When this entity was last changed ([ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)).</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ad&apos;s post ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostId { get; set; }
#nullable restore
#else
        public string PostId { get; set; }
#endif
        /// <summary>The ad&apos;s post URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostUrl { get; private set; }
#nullable restore
#else
        public string PostUrl { get; private set; }
#endif
        /// <summary>When the link for `preview_url` will no longer work. Set to `null` to disable the preview URL. [Learn how to update this field](https://ads-api.reddit.com/docs/v3/preview-an-ad).</summary>
        public DateTimeOffset? PreviewExpiry { get; set; }
        /// <summary>A URL to preview the ad in a placement. Available only while `preview_expiry` is valid. Append `?comment_ad={{Preview ID}}` to a post URL to preview in a different placement.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewUrl { get; private set; }
#nullable restore
#else
        public string PreviewUrl { get; private set; }
#endif
        /// <summary>Products associated with the ad. Up to 6 products.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdProduct>? Products { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdProduct> Products { get; set; }
#endif
        /// <summary>The ID of the ad post&apos;s author. Required for catalog sales campaigns.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileId { get; set; }
#nullable restore
#else
        public string ProfileId { get; set; }
#endif
        /// <summary>Why the ad was rejected.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsRejectionReason? RejectionReason { get; private set; }
        /// <summary>The shopping_creative property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingCreative? ShoppingCreative { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingCreative ShoppingCreative { get; set; }
#endif
        /// <summary>The skadnetwork_metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.SkadnetworkMetadata2? SkadnetworkMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.SkadnetworkMetadata2 SkadnetworkMetadata { get; set; }
#endif
        /// <summary>Optional supplementary or disclaimer text for the generated post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupplementaryText { get; set; }
#nullable restore
#else
        public string SupplementaryText { get; set; }
#endif
        /// <summary>Optional image asset identifiers used as video thumbnails.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>? ThumbnailAssetIdentifiers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId> ThumbnailAssetIdentifiers { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdPatch"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdPatch CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdPatch();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ad_account_id", n => { AdAccountId = n.GetStringValue(); } },
                { "ad_group_id", n => { AdGroupId = n.GetStringValue(); } },
                { "asset_identifiers", n => { AssetIdentifiers = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId.CreateFromDiscriminatorValue)?.AsList(); } },
                { "campaign_id", n => { CampaignId = n.GetStringValue(); } },
                { "campaign_objective_type", n => { CampaignObjectiveType = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.CampaignObjectiveType2>(); } },
                { "click_url", n => { ClickUrl = n.GetStringValue(); } },
                { "click_url_query_parameters", n => { ClickUrlQueryParameters = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "configured_status", n => { ConfiguredStatus = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ConfiguredStatus2>(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "delivery_status", n => { DeliveryStatus = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "destination", n => { Destination = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdPatchDestination>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdPatchDestination.CreateFromDiscriminatorValue); } },
                { "effective_status", n => { EffectiveStatus = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EffectiveStatus2>(); } },
                { "enhancements", n => { Enhancements = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesEnhancements>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesEnhancements.CreateFromDiscriminatorValue); } },
                { "event_trackers", n => { EventTrackers = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "modified_at", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "post_id", n => { PostId = n.GetStringValue(); } },
                { "post_url", n => { PostUrl = n.GetStringValue(); } },
                { "preview_expiry", n => { PreviewExpiry = n.GetDateTimeOffsetValue(); } },
                { "preview_url", n => { PreviewUrl = n.GetStringValue(); } },
                { "products", n => { Products = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdProduct>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdProduct.CreateFromDiscriminatorValue)?.AsList(); } },
                { "profile_id", n => { ProfileId = n.GetStringValue(); } },
                { "rejection_reason", n => { RejectionReason = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsRejectionReason>(); } },
                { "shopping_creative", n => { ShoppingCreative = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingCreative>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingCreative.CreateFromDiscriminatorValue); } },
                { "skadnetwork_metadata", n => { SkadnetworkMetadata = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.SkadnetworkMetadata2>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.SkadnetworkMetadata2.CreateFromDiscriminatorValue); } },
                { "supplementary_text", n => { SupplementaryText = n.GetStringValue(); } },
                { "thumbnail_asset_identifiers", n => { ThumbnailAssetIdentifiers = n.GetCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ad_account_id", AdAccountId);
            writer.WriteStringValue("ad_group_id", AdGroupId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>("asset_identifiers", AssetIdentifiers);
            writer.WriteStringValue("campaign_id", CampaignId);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.CampaignObjectiveType2>("campaign_objective_type", CampaignObjectiveType);
            writer.WriteStringValue("click_url", ClickUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaQueryParameter>("click_url_query_parameters", ClickUrlQueryParameters);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ConfiguredStatus2>("configured_status", ConfiguredStatus);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdPatchDestination>("destination", Destination);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPostCreativesEnhancements>("enhancements", Enhancements);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.EventTrackersItem>("event_trackers", EventTrackers);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("modified_at", ModifiedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("post_id", PostId);
            writer.WriteDateTimeOffsetValue("preview_expiry", PreviewExpiry);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaAdProduct>("products", Products);
            writer.WriteStringValue("profile_id", ProfileId);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaShoppingCreative>("shopping_creative", ShoppingCreative);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.SkadnetworkMetadata2>("skadnetwork_metadata", SkadnetworkMetadata);
            writer.WriteStringValue("supplementary_text", SupplementaryText);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaRmaxAssetId>("thumbnail_asset_identifiers", ThumbnailAssetIdentifiers);
        }
    }
}
#pragma warning restore CS0618
