// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The role of a creative asset within a post.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComponentsEnumStructuredPostCreativeAssetRole
    {
        [EnumMember(Value = "HEADLINE")]
        #pragma warning disable CS1591
        Headline,
        #pragma warning restore CS1591
        [EnumMember(Value = "IMAGE")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIDEO")]
        #pragma warning disable CS1591
        Video,
        #pragma warning restore CS1591
        [EnumMember(Value = "CTA")]
        #pragma warning disable CS1591
        Cta,
        #pragma warning restore CS1591
        [EnumMember(Value = "THUMBNAIL")]
        #pragma warning disable CS1591
        Thumbnail,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAROUSEL_ITEM")]
        #pragma warning disable CS1591
        CarouselItem,
        #pragma warning restore CS1591
        [EnumMember(Value = "HERO")]
        #pragma warning disable CS1591
        Hero,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECONDARY_IMAGE")]
        #pragma warning disable CS1591
        SecondaryImage,
        #pragma warning restore CS1591
    }
}
