// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListCustomAudience"/>, <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaEngagementRetargetingCustomAudience"/>, <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPixelRetargetingCustomAudience"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComponentsSchemaCustomAudience : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListCustomAudience"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListCustomAudience? ComponentsSchemaCustomerListCustomAudience { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListCustomAudience ComponentsSchemaCustomerListCustomAudience { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaEngagementRetargetingCustomAudience"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaEngagementRetargetingCustomAudience? ComponentsSchemaEngagementRetargetingCustomAudience { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaEngagementRetargetingCustomAudience ComponentsSchemaEngagementRetargetingCustomAudience { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPixelRetargetingCustomAudience"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPixelRetargetingCustomAudience? ComponentsSchemaPixelRetargetingCustomAudience { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPixelRetargetingCustomAudience ComponentsSchemaPixelRetargetingCustomAudience { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomAudience"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomAudience CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomAudience();
            if("ComponentsSchemaCustomerListCustomAudience".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ComponentsSchemaCustomerListCustomAudience = new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListCustomAudience();
            }
            else if("ComponentsSchemaEngagementRetargetingCustomAudience".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ComponentsSchemaEngagementRetargetingCustomAudience = new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaEngagementRetargetingCustomAudience();
            }
            else if("ComponentsSchemaPixelRetargetingCustomAudience".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ComponentsSchemaPixelRetargetingCustomAudience = new global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPixelRetargetingCustomAudience();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ComponentsSchemaCustomerListCustomAudience != null)
            {
                return ComponentsSchemaCustomerListCustomAudience.GetFieldDeserializers();
            }
            else if(ComponentsSchemaEngagementRetargetingCustomAudience != null)
            {
                return ComponentsSchemaEngagementRetargetingCustomAudience.GetFieldDeserializers();
            }
            else if(ComponentsSchemaPixelRetargetingCustomAudience != null)
            {
                return ComponentsSchemaPixelRetargetingCustomAudience.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ComponentsSchemaCustomerListCustomAudience != null)
            {
                writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaCustomerListCustomAudience>(null, ComponentsSchemaCustomerListCustomAudience);
            }
            else if(ComponentsSchemaEngagementRetargetingCustomAudience != null)
            {
                writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaEngagementRetargetingCustomAudience>(null, ComponentsSchemaEngagementRetargetingCustomAudience);
            }
            else if(ComponentsSchemaPixelRetargetingCustomAudience != null)
            {
                writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaPixelRetargetingCustomAudience>(null, ComponentsSchemaPixelRetargetingCustomAudience);
            }
        }
    }
}
#pragma warning restore CS0618
