// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>
    /// The cost information for audiences using third-party data providers.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Cost : IParsable
    {
        /// <summary>The currency symbol used ([ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)).</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsCurrency? Currency { get; set; }
        /// <summary>The conversion rate from local currency to USD (micro units). Omitted if currency is already USD or unavailable.</summary>
        public int? CurrencyConversionRateToUsd { get; set; }
        /// <summary>Whether this cost is exempted from being passed to the advertiser.</summary>
        public bool? IsCostExempted { get; set; }
        /// <summary>The audience&apos;s data provider.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaThirdPartyDataCostPartner? Partner { get; set; }
        /// <summary>The data provider&apos;s segment ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartnerSegmentId { get; set; }
#nullable restore
#else
        public string PartnerSegmentId { get; set; }
#endif
        /// <summary>The data&apos;s cost (local microcurrency). For example, `2750000` is $2.75 for CPM pricing.</summary>
        public int? Price { get; set; }
        /// <summary>The data&apos;s pricing model.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.CpmRateType? RateType { get; set; }
        /// <summary>The Reddit audience ID. Populated for custom audiences, omitted for third-party audiences.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedditAudienceId { get; set; }
#nullable restore
#else
        public string RedditAudienceId { get; set; }
#endif
        /// <summary>When the cost was last updated (Unix timestamp in milliseconds). Omitted for third-party audiences when unavailable.</summary>
        public long? UpdateTimestamp { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.Cost"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.Cost CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.Cost();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currency", n => { Currency = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsCurrency>(); } },
                { "currency_conversion_rate_to_usd", n => { CurrencyConversionRateToUsd = n.GetIntValue(); } },
                { "is_cost_exempted", n => { IsCostExempted = n.GetBoolValue(); } },
                { "partner", n => { Partner = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaThirdPartyDataCostPartner>(); } },
                { "partner_segment_id", n => { PartnerSegmentId = n.GetStringValue(); } },
                { "price", n => { Price = n.GetIntValue(); } },
                { "rate_type", n => { RateType = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.CpmRateType>(); } },
                { "reddit_audience_id", n => { RedditAudienceId = n.GetStringValue(); } },
                { "update_timestamp", n => { UpdateTimestamp = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsCurrency>("currency", Currency);
            writer.WriteIntValue("currency_conversion_rate_to_usd", CurrencyConversionRateToUsd);
            writer.WriteBoolValue("is_cost_exempted", IsCostExempted);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaThirdPartyDataCostPartner>("partner", Partner);
            writer.WriteStringValue("partner_segment_id", PartnerSegmentId);
            writer.WriteIntValue("price", Price);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.CpmRateType>("rate_type", RateType);
            writer.WriteStringValue("reddit_audience_id", RedditAudienceId);
            writer.WriteLongValue("update_timestamp", UpdateTimestamp);
        }
    }
}
#pragma warning restore CS0618
