// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateCatalogRequestData : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The catalog&apos;s default currency.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.DefaultCurrency? DefaultCurrency { get; set; }
        /// <summary>The catalog&apos;s default language.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.DefaultLanguage? DefaultLanguage { get; set; }
        /// <summary>The attached Reddit Pixel IDs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EventSources { get; set; }
#nullable restore
#else
        public List<string> EventSources { get; set; }
#endif
        /// <summary>The product catalog&apos;s name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.CreateCatalogRequestData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.CreateCatalogRequestData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.CreateCatalogRequestData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default_currency", n => { DefaultCurrency = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.DefaultCurrency>(); } },
                { "default_language", n => { DefaultLanguage = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.DefaultLanguage>(); } },
                { "event_sources", n => { EventSources = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.DefaultCurrency>("default_currency", DefaultCurrency);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.DefaultLanguage>("default_language", DefaultLanguage);
            writer.WriteCollectionOfPrimitiveValues<string>("event_sources", EventSources);
            writer.WriteStringValue("name", Name);
        }
    }
}
#pragma warning restore CS0618
