// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>Type of the custom audience. For engagement retargeting audiences, this value is always ENGAGEMENT_RETARGETING.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EngagementRetargetingType
    {
        [EnumMember(Value = "ENGAGEMENT_RETARGETING")]
        #pragma warning disable CS1591
        EngagementRetargeting,
        #pragma warning restore CS1591
    }
}
