// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The [gender group](https://business.reddithelp.com/s/article/demographics#gender-targeting) to target.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Gender
    {
        [EnumMember(Value = "FEMALE")]
        #pragma warning disable CS1591
        Female,
        #pragma warning restore CS1591
        [EnumMember(Value = "MALE")]
        #pragma warning disable CS1591
        Male,
        #pragma warning restore CS1591
    }
}
