// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The industry type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Industry
    {
        [EnumMember(Value = "ADULT")]
        #pragma warning disable CS1591
        Adult,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADVERTISING")]
        #pragma warning disable CS1591
        Advertising,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALCOHOL")]
        #pragma warning disable CS1591
        Alcohol,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTO")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOTHING_AND_FASHION")]
        #pragma warning disable CS1591
        ClothingAndFashion,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONSULTING")]
        #pragma warning disable CS1591
        Consulting,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONSUMER_PACKAGED_GOODS")]
        #pragma warning disable CS1591
        ConsumerPackagedGoods,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATING")]
        #pragma warning disable CS1591
        Dating,
        #pragma warning restore CS1591
        [EnumMember(Value = "EDUCATION")]
        #pragma warning disable CS1591
        Education,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMPLOYMENT")]
        #pragma warning disable CS1591
        Employment,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENTERTAINMENT")]
        #pragma warning disable CS1591
        Entertainment,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINANCIAL_SERVICES")]
        #pragma warning disable CS1591
        FinancialServices,
        #pragma warning restore CS1591
        [EnumMember(Value = "GAMBLING_AND_FANTASY_SPORTS")]
        #pragma warning disable CS1591
        GamblingAndFantasySports,
        #pragma warning restore CS1591
        [EnumMember(Value = "GAMING")]
        #pragma warning disable CS1591
        Gaming,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEALTH_AND_BEAUTY")]
        #pragma warning disable CS1591
        HealthAndBeauty,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "POLITICS_AND_GOVERNMENT")]
        #pragma warning disable CS1591
        PoliticsAndGovernment,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUBLISHING")]
        #pragma warning disable CS1591
        Publishing,
        #pragma warning restore CS1591
        [EnumMember(Value = "REAL_ESTATE")]
        #pragma warning disable CS1591
        RealEstate,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESTAURANTS_AND_FOOD")]
        #pragma warning disable CS1591
        RestaurantsAndFood,
        #pragma warning restore CS1591
        [EnumMember(Value = "RETAIL_AND_ECOMMERCE")]
        #pragma warning disable CS1591
        RetailAndEcommerce,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPORTS")]
        #pragma warning disable CS1591
        Sports,
        #pragma warning restore CS1591
        [EnumMember(Value = "TECH_B2B")]
        #pragma warning disable CS1591
        TechB2B,
        #pragma warning restore CS1591
        [EnumMember(Value = "TECH_B2C")]
        #pragma warning disable CS1591
        TechB2C,
        #pragma warning restore CS1591
        [EnumMember(Value = "TECH_OTHER")]
        #pragma warning disable CS1591
        TechOther,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAVEL")]
        #pragma warning disable CS1591
        Travel,
        #pragma warning restore CS1591
    }
}
