// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LduItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "LDU")]
        #pragma warning disable CS1591
        Ldu,
        #pragma warning restore CS1591
    }
}
