// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The [post type](https://business.reddithelp.com/s/article/Reddit-Ad-Unit-Specifications#ad-types).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListStructuredPostsTypeParameter
    {
        [EnumMember(Value = "CAROUSEL")]
        #pragma warning disable CS1591
        Carousel,
        #pragma warning restore CS1591
        [EnumMember(Value = "IMAGE")]
        #pragma warning disable CS1591
        Image,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEXT")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "VIDEO")]
        #pragma warning disable CS1591
        Video,
        #pragma warning restore CS1591
    }
}
