// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The job is still processing.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProcessingStatus
    {
        [EnumMember(Value = "PROCESSING")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
    }
}
