// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The product creation status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProductsCreateResponseDataItemStatus
    {
        [EnumMember(Value = "CREATED")]
        #pragma warning disable CS1591
        Created,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPDATED")]
        #pragma warning disable CS1591
        Updated,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID")]
        #pragma warning disable CS1591
        Invalid,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNCHANGED")]
        #pragma warning disable CS1591
        Unchanged,
        #pragma warning restore CS1591
    }
}
