// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The warning severity.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProductsCreateResponseDataItemIssuesItemSeverity
    {
        [EnumMember(Value = "WARNING")]
        #pragma warning disable CS1591
        Warning,
        #pragma warning restore CS1591
        [EnumMember(Value = "CRITICAL")]
        #pragma warning disable CS1591
        Critical,
        #pragma warning restore CS1591
    }
}
