// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The creative type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PromotedCommunityPostType
    {
        [EnumMember(Value = "PROMOTED_COMMUNITY_POST")]
        #pragma warning disable CS1591
        PromotedCommunityPost,
        #pragma warning restore CS1591
    }
}
