// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The event type. Use `REMINDER` for reminder ads.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReminderType
    {
        [EnumMember(Value = "REMINDER")]
        #pragma warning disable CS1591
        Reminder,
        #pragma warning restore CS1591
    }
}
