// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>Indicates the catalog sale ad group&apos;s type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ShoppingType2
    {
        [EnumMember(Value = "DYNAMIC")]
        #pragma warning disable CS1591
        Dynamic,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATIC")]
        #pragma warning disable CS1591
        StaticValue,
        #pragma warning restore CS1591
    }
}
