// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The type of ads an ad group should contain for shopping ads.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ShoppingType
    {
        [EnumMember(Value = "DYNAMIC")]
        #pragma warning disable CS1591
        Dynamic,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATIC")]
        #pragma warning disable CS1591
        StaticValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
