// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The custom audience&apos;s processing status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Status
    {
        [EnumMember(Value = "VALID")]
        #pragma warning disable CS1591
        Valid,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUCCESSFUL")]
        #pragma warning disable CS1591
        Successful,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_ERROR")]
        #pragma warning disable CS1591
        UserError,
        #pragma warning restore CS1591
        [EnumMember(Value = "SERVER_ERROR")]
        #pragma warning disable CS1591
        ServerError,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETED")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_ENOUGH_MATCHES_ERROR")]
        #pragma warning disable CS1591
        NotEnoughMatchesError,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_DATA_SOURCE")]
        #pragma warning disable CS1591
        InvalidDataSource,
        #pragma warning restore CS1591
    }
}
