// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>The job completed successfully.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SuccessStatus
    {
        [EnumMember(Value = "SUCCESS")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
    }
}
