// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SuggestBidRequestData : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ad account ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdAccountId { get; set; }
#nullable restore
#else
        public string AdAccountId { get; set; }
#endif
        /// <summary>The attribution conversion type. Valid for cost-per-action (CPA) bid types. Also configures the attribution type to query when calculating effective-cost-per-action (eCPA) fields.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsAttributionType? AttributionType { get; set; }
        /// <summary>The ad group&apos;s bid strategy. For CBO campaigns, this must match the campaign&apos;s bid strategy.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.BidStrategy? BidStrategy { get; set; }
        /// <summary>The ad group&apos;s [bidding strategy](https://business.reddithelp.com/s/article/How-much-do-Reddit-Ads-cost#bidding-strategies).</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.BidType3? BidType { get; set; }
        /// <summary>The [campaign objective](https://business.reddithelp.com/s/article/Ad-campaign-objectives).</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.Objective? CampaignObjective { get; set; }
        /// <summary>The currency symbol used ([ISO 4217](https://www.iso.org/iso-4217-currency-codes.html)).</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsCurrency? Currency { get; set; }
        /// <summary>The duration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.SuggestBidRequestDataDuration? Duration { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.SuggestBidRequestDataDuration Duration { get; set; }
#endif
        /// <summary>DEPRECATED: This field is no longer used. It will be ignored if provided. Use `data.duration.end_time` instead.</summary>
        [Obsolete("")]
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>The goal objective of the ad group.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsGoalType? GoalType { get; set; }
        /// <summary>The goal value (microcurrency).</summary>
        public int? GoalValue { get; set; }
        /// <summary>Whether the ad group belongs to a CBO (campaign budget optimization) campaign. This cannot be modified with the API.</summary>
        public bool? IsCampaignBudgetOptimization { get; private set; }
        /// <summary>The event you want to measure. Must match the campaign&apos;s optimization goal for CBO campaigns. Set to `NULL` for conversions or app installs objectives to default from the campaign. **This can&apos;t be changed later.** See the [goal options](https://ads-api.reddit.com/docs/v3/operations/Create%20Ad%20Group#optimization-goal-options).</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.OptimizationGoal? OptimizationGoal { get; set; }
        /// <summary>DEPRECATED: This field is no longer used. It will be ignored if provided. Use `data.duration.start_time` instead.</summary>
        [Obsolete("")]
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>The targeting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargeting? Targeting { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargeting Targeting { get; set; }
#endif
        /// <summary>The type of view-through conversion being measured. For ad groups under CBO campaigns, this field must match the campaign&apos;s `view_through_conversion_type`.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsViewThroughConversionType? ViewThroughConversionType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.SuggestBidRequestData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.SuggestBidRequestData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.SuggestBidRequestData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ad_account_id", n => { AdAccountId = n.GetStringValue(); } },
                { "attribution_type", n => { AttributionType = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsAttributionType>(); } },
                { "bid_strategy", n => { BidStrategy = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.BidStrategy>(); } },
                { "bid_type", n => { BidType = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.BidType3>(); } },
                { "campaign_objective", n => { CampaignObjective = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.Objective>(); } },
                { "currency", n => { Currency = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsCurrency>(); } },
                { "duration", n => { Duration = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.SuggestBidRequestDataDuration>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.SuggestBidRequestDataDuration.CreateFromDiscriminatorValue); } },
                { "end_time", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "goal_type", n => { GoalType = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsGoalType>(); } },
                { "goal_value", n => { GoalValue = n.GetIntValue(); } },
                { "is_campaign_budget_optimization", n => { IsCampaignBudgetOptimization = n.GetBoolValue(); } },
                { "optimization_goal", n => { OptimizationGoal = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.OptimizationGoal>(); } },
                { "start_time", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "targeting", n => { Targeting = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargeting>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargeting.CreateFromDiscriminatorValue); } },
                { "view_through_conversion_type", n => { ViewThroughConversionType = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsViewThroughConversionType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ad_account_id", AdAccountId);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsAttributionType>("attribution_type", AttributionType);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.BidStrategy>("bid_strategy", BidStrategy);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.BidType3>("bid_type", BidType);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.Objective>("campaign_objective", CampaignObjective);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsCurrency>("currency", Currency);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.SuggestBidRequestDataDuration>("duration", Duration);
            writer.WriteDateTimeOffsetValue("end_time", EndTime);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsGoalType>("goal_type", GoalType);
            writer.WriteIntValue("goal_value", GoalValue);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.OptimizationGoal>("optimization_goal", OptimizationGoal);
            writer.WriteDateTimeOffsetValue("start_time", StartTime);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsSchemaTargeting>("targeting", Targeting);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.ComponentsEnumsViewThroughConversionType>("view_through_conversion_type", ViewThroughConversionType);
        }
    }
}
#pragma warning restore CS0618
