// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    /// <summary>Why this ad account was suspended.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SuspensionReason
    {
        [EnumMember(Value = "ADVERTISING_POLICY")]
        #pragma warning disable CS1591
        AdvertisingPolicy,
        #pragma warning restore CS1591
        [EnumMember(Value = "BEHAVIOR")]
        #pragma warning disable CS1591
        Behavior,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD")]
        #pragma warning disable CS1591
        Fraud,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "KYC_CHECK_FAILED")]
        #pragma warning disable CS1591
        KycCheckFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD_MALWARE")]
        #pragma warning disable CS1591
        FraudMalware,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD_FINANCIAL_SCAMS")]
        #pragma warning disable CS1591
        FraudFinancialScams,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD_PHISHING")]
        #pragma warning disable CS1591
        FraudPhishing,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD_IMPERSONATION")]
        #pragma warning disable CS1591
        FraudImpersonation,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD_SUSPENSION_EVASION")]
        #pragma warning disable CS1591
        FraudSuspensionEvasion,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD_DISPUTE")]
        #pragma warning disable CS1591
        FraudDispute,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRAUD_DECEPTION")]
        #pragma warning disable CS1591
        FraudDeception,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
