// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateSavedAudienceRequestData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The saved audience status.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.Status3? Status { get; set; }
        /// <summary>Targeting information for the ad group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.Targeting2? Targeting { get; set; }
#nullable restore
#else
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.Targeting2 Targeting { get; set; }
#endif
        /// <summary>The saved audience type.</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Models.Type4? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.UpdateSavedAudienceRequestData"/> and sets the default values.
        /// </summary>
        public UpdateSavedAudienceRequestData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Models.UpdateSavedAudienceRequestData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Reddit.Ads.OpenApiClient.Models.UpdateSavedAudienceRequestData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Reddit.Ads.OpenApiClient.Models.UpdateSavedAudienceRequestData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "name", n => { Name = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.Status3>(); } },
                { "targeting", n => { Targeting = n.GetObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.Targeting2>(global::Soenneker.Reddit.Ads.OpenApiClient.Models.Targeting2.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.Type4>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.Status3>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.Targeting2>("targeting", Targeting);
            writer.WriteEnumValue<global::Soenneker.Reddit.Ads.OpenApiClient.Models.Type4>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
