// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Reddit.Ads.OpenApiClient.Pixels.Item.Conversion_events;
using Soenneker.Reddit.Ads.OpenApiClient.Pixels.Item.Last_fired_at;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Pixels.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \pixels\{pixelId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPixelItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The conversion_events property</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Pixels.Item.Conversion_events.Conversion_eventsRequestBuilder Conversion_events
        {
            get => new global::Soenneker.Reddit.Ads.OpenApiClient.Pixels.Item.Conversion_events.Conversion_eventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The last_fired_at property</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Pixels.Item.Last_fired_at.Last_fired_atRequestBuilder Last_fired_at
        {
            get => new global::Soenneker.Reddit.Ads.OpenApiClient.Pixels.Item.Last_fired_at.Last_fired_atRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Pixels.Item.WithPixelItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPixelItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pixels/{pixelId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Pixels.Item.WithPixelItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPixelItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pixels/{pixelId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
