// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Reddit.Ads.OpenApiClient.Product_sets.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Product_sets
{
    /// <summary>
    /// Builds and executes requests for operations under \product_sets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Product_setsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Reddit.Ads.OpenApiClient.product_sets.item collection</summary>
        /// <param name="position">The product set ID.</param>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Product_sets.Item.WithProductSetItemRequestBuilder"/></returns>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Product_sets.Item.WithProductSetItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("productSetId", position);
                return new global::Soenneker.Reddit.Ads.OpenApiClient.Product_sets.Item.WithProductSetItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Product_sets.Product_setsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Product_setsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/product_sets", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Product_sets.Product_setsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Product_setsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/product_sets", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
