// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Uploads.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Uploads
{
    /// <summary>
    /// Builds and executes requests for operations under \creative_assets\uploads
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UploadsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Reddit.Ads.OpenApiClient.creative_assets.uploads.item collection</summary>
        /// <param name="position">The creative asset upload ID.</param>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Uploads.Item.UploadsItemRequestBuilder"/></returns>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Uploads.Item.UploadsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Uploads.Item.UploadsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Uploads.UploadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UploadsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/creative_assets/uploads", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Uploads.UploadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UploadsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/creative_assets/uploads", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
