// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Reddit.Ads.OpenApiClient.Funding_instruments.Item.Allocations;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Funding_instruments.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \funding_instruments\{fundingInstrumentId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFundingInstrumentItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The allocations property</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Funding_instruments.Item.Allocations.AllocationsRequestBuilder Allocations
        {
            get => new global::Soenneker.Reddit.Ads.OpenApiClient.Funding_instruments.Item.Allocations.AllocationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Funding_instruments.Item.WithFundingInstrumentItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFundingInstrumentItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/funding_instruments/{fundingInstrumentId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Funding_instruments.Item.WithFundingInstrumentItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFundingInstrumentItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/funding_instruments/{fundingInstrumentId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
