// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Reddit.Ads.OpenApiClient.Ad_groups.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Ad_groups
{
    /// <summary>
    /// Builds and executes requests for operations under \ad_groups
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Ad_groupsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Reddit.Ads.OpenApiClient.ad_groups.item collection</summary>
        /// <param name="position">The ad group ID.</param>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Ad_groups.Item.WithAdGroupItemRequestBuilder"/></returns>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Ad_groups.Item.WithAdGroupItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("adGroupId", position);
                return new global::Soenneker.Reddit.Ads.OpenApiClient.Ad_groups.Item.WithAdGroupItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Ad_groups.Ad_groupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Ad_groupsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ad_groups", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Ad_groups.Ad_groupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Ad_groupsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ad_groups", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
