// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Item;
using Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Uploads;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Reddit.Ads.OpenApiClient.Creative_assets
{
    /// <summary>
    /// Builds and executes requests for operations under \creative_assets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Creative_assetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The uploads property</summary>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Uploads.UploadsRequestBuilder Uploads
        {
            get => new global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Uploads.UploadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Reddit.Ads.OpenApiClient.creative_assets.item collection</summary>
        /// <param name="position">The creative asset ID.</param>
        /// <returns>A <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Item.WithCreativeAssetItemRequestBuilder"/></returns>
        public global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Item.WithCreativeAssetItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("creativeAssetId", position);
                return new global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Item.WithCreativeAssetItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Creative_assetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Creative_assetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/creative_assets", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Reddit.Ads.OpenApiClient.Creative_assets.Creative_assetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Creative_assetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/creative_assets", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
